;;; build-play-bundle.el --- build the live play bundle without Node -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'bytecomp)

(defconst gr-build-repo-root
  (expand-file-name ".." (file-name-directory (or load-file-name buffer-file-name))))

(defvar gr-conditional-suppress-main t)
(setq gr-conditional-suppress-main t)
(load (expand-file-name "conditional-runtime-check.el" (file-name-directory (or load-file-name buffer-file-name))) nil t)

(defconst gr-build-runtime-dir
  (expand-file-name "nelisp_runtime" gr-build-repo-root))

(defconst gr-build-build-dir
  (expand-file-name "build" gr-build-repo-root))

(defconst gr-build-emacs-home
  (expand-file-name "emacs-home" gr-build-build-dir))

(defconst gr-build-compile-log-path
  (expand-file-name "play-byte-compile.log" gr-build-build-dir))

(defconst gr-build-loader-path
  (expand-file-name "play-bundle-loader.el" gr-build-build-dir))

(defconst gr-build-runtime-files
  '("game-runner.el"
    "gamedata-simple.el"
    "gamedata-conditional.el"
    "gamedata-state.el"
    "sumi-json.el"
    "play.el"))

(defconst gr-build-byte-compile-files
  (cl-remove "gamedata-conditional.el" gr-build-runtime-files :test #'string=))

(defun gr-build-ensure-generated-runtime-present ()
  "Require checked-in/generated elisp runtime files to exist."
  (dolist (file '("gamedata-simple.el" "gamedata-conditional.el"))
    (let ((path (expand-file-name file gr-build-runtime-dir)))
      (unless (file-exists-p path)
        (error "missing elisp runtime source: %s" path)))))

(defun gr-build-normalize-path (path)
  "Return PATH as an absolute slash-separated path."
  (replace-regexp-in-string "\\\\" "/" (expand-file-name path) nil t))

(defun gr-build-loader-form (file)
  "Return a loader form for runtime FILE."
  (let* ((absolute (expand-file-name file gr-build-runtime-dir))
         (load-path (if (string= file "gamedata-conditional.el")
                        absolute
                      (file-name-sans-extension absolute))))
    (format "(load %S nil t)" (gr-build-normalize-path load-path))))

(defun gr-build-write-loader ()
  "Write the play bundle loader."
  (with-temp-file gr-build-loader-path
    (insert ";;; play-bundle-loader.el --- load compiled play runtime -*- coding: utf-8; lexical-binding: t; -*-\n")
    (insert ";; Generated by nelisp_runtime/build-play-bundle.el. Prefer .elc when present.\n")
    (dolist (file gr-build-runtime-files)
      (insert (gr-build-loader-form file) "\n"))
    (insert "\n")))

(defun gr-build-byte-compile-runtime ()
  "Byte-compile runtime files and write the compile log."
  (setq byte-compile-error-on-warn nil)
  (let ((default-directory gr-build-repo-root)
        (files (mapcar (lambda (file)
                         (expand-file-name file gr-build-runtime-dir))
                       gr-build-byte-compile-files))
        (log-buffer (get-buffer-create " *gr-build-byte-compile*")))
    (with-current-buffer log-buffer
      (erase-buffer))
    (let ((standard-output log-buffer))
      (dolist (file files)
        (let ((elc (byte-compile-dest-file file)))
          (when (file-exists-p elc)
            (delete-file elc)))
        (byte-compile-file file)))
    (with-current-buffer log-buffer
      (write-region (point-min) (point-max) gr-build-compile-log-path nil 'silent))))

(defun gr-build-main ()
  "Build the live play bundle using only Emacs Lisp."
  (make-directory gr-build-build-dir t)
  (make-directory gr-build-emacs-home t)
  (gr-build-ensure-generated-runtime-present)
  (princ "STATE-DIFF-ELISP-SOURCE using checked-in elisp gamedata\n")
  (gr-conditional-main)
  (let ((conditional-elc (expand-file-name "gamedata-conditional.elc" gr-build-runtime-dir)))
    (when (file-exists-p conditional-elc)
      (delete-file conditional-elc)))
  (gr-build-byte-compile-runtime)
  (gr-build-write-loader)
  (princ
   (format
    "{\n  \"loader\": \"build/play-bundle-loader.el\",\n  \"compileLog\": \"build/play-byte-compile.log\",\n  \"compiled\": [%s],\n  \"sourceLoaded\": [\"gamedata-conditional.el\"],\n  \"builder\": \"nelisp_runtime/build-play-bundle.el\"\n}\n"
    (mapconcat (lambda (file) (format "%S" file)) gr-build-byte-compile-files ", "))))

(when noninteractive
  (gr-build-main))

;;; build-play-bundle.el ends here
