;;; run-battle.el --- battle core verification -*- coding: utf-8; -*-

(defvar gr-battle-orig-func080 nil)
(defvar gr-battle-orig-func009 nil)
(defvar gr-battle-orig-func019 nil)
(defvar gr-battle-script nil)
(defvar gr-battle-script-index 0)
(defvar gr-battle-current-key 0)
(defvar gr-battle-turn-count 0)
(defvar gr-battle-frame-count 0)
(defvar gr-battle-frame-limit 4)
(defvar gr-battle-enemy-index 0)
(defvar gr-battle-error nil)

(defun gr-battle-read-key-state (keycode)
  "Return scripted key state for KEYCODE."
  (if (equal (gr-num keycode) gr-battle-current-key) 1 0))

(defun gr-battle-set-cell (grid x y value)
  "Set GRID[X][Y] to VALUE when the coordinates are in range."
  (let ((row (and (vectorp grid) (gr-index-ref grid x))))
    (when (and (vectorp row) (>= y 0) (< y (length row)))
      (aset row y value))))

(defun gr-battle-find-enemy ()
  "Return the first live enemy slot."
  (let ((rows (gr-get 83))
        (idx 1)
        (found 0))
    (while (and (vectorp rows) (< idx (length rows)) (equal found 0))
      (when (and (not (equal (gr-prop-ref (aref rows idx) "Var0") 0))
                 (not (equal (gr-prop-ref (aref rows idx) "Var0") 50))
                 (> (gr-num (or (gr-prop-ref (aref rows idx) "Var3") 0)) 0))
        (setq found idx))
      (setq idx (1+ idx)))
    found))

(defun gr-battle-clear-other-enemies (keep-idx)
  "Zero every enemy row except KEEP-IDX and clear the occupancy map."
  (let ((rows (gr-get 83))
        (occ (gr-get 82))
        (idx 1)
        (row nil)
        (x 0)
        (y 0)
        (slot 0))
    (while (and (vectorp rows) (< idx (length rows)))
      (setq row (aref rows idx))
      (setq x (gr-num (or (gr-prop-ref row "Var1") 0)))
      (setq y (gr-num (or (gr-prop-ref row "Var2") 0)))
      (when (and (> x 0) (> y 0))
        (gr-battle-set-cell occ x y 0))
      (unless (equal idx keep-idx)
        (setq slot 0)
        (while (< slot (length row))
          (aset row slot 0)
          (setq slot (1+ slot))))
      (setq idx (1+ idx)))
    (gr-set 97 1)))

(defun gr-battle-enemy-hp ()
  "Return the tracked battle enemy HP."
  (let ((rows (gr-get 83)))
    (if (and (vectorp rows)
             (> gr-battle-enemy-index 0)
             (< gr-battle-enemy-index (length rows)))
        (gr-num (or (gr-prop-ref (aref rows gr-battle-enemy-index) "Var3") 0))
      0)))

(defun gr-battle-enemy-alive-p ()
  "Return non-nil when the tracked enemy still exists."
  (let ((rows (gr-get 83)))
    (and (vectorp rows)
         (> gr-battle-enemy-index 0)
         (< gr-battle-enemy-index (length rows))
         (not (equal (gr-prop-ref (aref rows gr-battle-enemy-index) "Var0") 0)))))

(defun gr-battle-wrap-func080 (&rest args)
  "Feed one scripted key into func080."
  (setq gr-battle-current-key
        (if (< gr-battle-script-index (length gr-battle-script))
            (nth gr-battle-script-index gr-battle-script)
          0))
  (setq gr-battle-script-index (1+ gr-battle-script-index))
  (apply gr-battle-orig-func080 args))

(defun gr-battle-wrap-func009 (&rest args)
  "Stop when the post-battle player turn is reached."
  (setq gr-battle-frame-count (1+ gr-battle-frame-count))
  (when (> gr-battle-frame-count gr-battle-frame-limit)
    (throw 'gr-battle-stop 'frame-limit))
  (when (and (>= gr-battle-turn-count 1)
             (> gr-battle-script-index (length gr-battle-script)))
    (throw 'gr-battle-stop 'done))
  (apply gr-battle-orig-func009 args))

(defun gr-battle-wrap-func019 (&rest args)
  "Log one full battle turn around func019."
  (let ((enemy-before (gr-battle-enemy-hp))
        (player-before (gr-num (or (gr-get 211) 0))))
    (apply gr-battle-orig-func019 args)
    (setq gr-battle-turn-count (1+ gr-battle-turn-count))
    (princ (format "BATTLE-TURN %s enemy=%s->%s player=%s->%s\n"
                   gr-battle-turn-count
                   enemy-before
                   (gr-battle-enemy-hp)
                   player-before
                   (gr-num (or (gr-get 211) 0))))))

(defun gr-battle-install-wrappers ()
  "Install scripted-input wrappers for battle verification."
  (setq gr-battle-orig-func080 (gethash "func080" gr-native-funcs))
  (setq gr-battle-orig-func009 (gethash "func009" gr-native-funcs))
  (setq gr-battle-orig-func019 (gethash "func019" gr-native-funcs))
  (gr-defnative "func080" #'gr-battle-wrap-func080)
  (gr-defnative "func009" #'gr-battle-wrap-func009)
  (gr-defnative "func019" #'gr-battle-wrap-func019)
  (setq gr-read-key-state-fn #'gr-battle-read-key-state)
  (setq gr-reset-key-fn nil))

(defun gr-battle-restore-wrappers ()
  "Restore original battle wrapper targets."
  (when gr-battle-orig-func080
    (gr-defnative "func080" gr-battle-orig-func080))
  (when gr-battle-orig-func009
    (gr-defnative "func009" gr-battle-orig-func009))
  (when gr-battle-orig-func019
    (gr-defnative "func019" gr-battle-orig-func019))
  (setq gr-read-key-state-fn nil)
  (setq gr-reset-key-fn nil))

(defun gr-battle-place-adjacent-enemy ()
  "Move one real generated enemy next to the player and make it one-hit."
  (let* ((enemy-idx (gr-battle-find-enemy))
         (rows (gr-get 83))
         (occ (gr-get 82))
         (tiles (gr-get 71))
         (row nil)
         (px (gr-num (or (gr-get 66) 0)))
         (py (gr-num (or (gr-get 67) 0)))
         (tx 0)
         (dir 6)
         (oldx 0)
         (oldy 0))
    (if (equal enemy-idx 0)
        nil
      (setq gr-battle-enemy-index enemy-idx)
      (gr-battle-clear-other-enemies enemy-idx)
      (setq row (aref rows enemy-idx))
      (setq oldx (gr-num (or (gr-prop-ref row "Var1") 0)))
      (setq oldy (gr-num (or (gr-prop-ref row "Var2") 0)))
      (setq tx (if (< (1+ px) (gr-num (or (gr-get 33) 0)))
                   (1+ px)
                 (1- px)))
      (when (<= tx 0)
        (setq tx (1+ px)))
      (when (< tx px)
        (setq dir 4))
      (gr-battle-set-cell occ oldx oldy 0)
      (gr-battle-set-cell tiles px py 1)
      (gr-battle-set-cell tiles tx py 1)
      (gr-battle-set-cell occ tx py enemy-idx)
      (gr-prop-set row "Var1" tx)
      (gr-prop-set row "Var2" py)
      (gr-prop-set row "Var3" 1)
      (gr-prop-set row "Var7" 0)
      (gr-prop-set row "Var8" 0)
      (gr-prop-set row "Var9" 0)
      (gr-prop-set row "Var12" 0)
      (gr-prop-set row "Var13" 0)
      (gr-prop-set row "Var15" 0)
      (gr-prop-set row "Var17" 0)
      (gr-prop-set row "Var18" 0)
      (gr-prop-set row "Var20" 0)
      (gr-set 199 dir)
      t)))

(let* ((runtime-dir (file-name-directory (or load-file-name buffer-file-name)))
       (repo-root (expand-file-name ".." runtime-dir))
       (test-root (expand-file-name "build/battle-test-data" repo-root))
       (z-key 0)
       (result "BATTLE-PARTIAL"))
  (load-file (expand-file-name "game-runner.el" runtime-dir))
  (load-file (expand-file-name "gamedata-simple.el" runtime-dir))
  (load-file (expand-file-name "gamedata-conditional.el" runtime-dir))
  (setq gr-worldgen-autorun nil)
  (load-file (expand-file-name "run-worldgen.el" runtime-dir))
  (setq max-lisp-eval-depth 10000)
  (setq max-specpdl-size 10000)
  (make-directory test-root t)
  (let ((source-00 (expand-file-name "00.dat" gr-data-root))
        (target-00 (expand-file-name "00.dat" test-root)))
    (when (file-exists-p source-00)
      (copy-file source-00 target-00 t)))
  (setq gr-data-root (or (getenv "GR_DATA_ROOT") test-root))
  (gr-reset)
  (gr-set "stat" 1)
  (gr-set "hwnd" 0)
  (gr-run-func "func004")
  (gr-worldgen-seed-base-state)
  (gr-worldgen-run t)
  (gr-set 211 (max 15 (gr-num (or (gr-get 211) 0))))
  (gr-set 212 0)
  (gr-set 213 0)
  (gr-set 214 0)
  (gr-set 217 0)
  (gr-set 218 0)
  (gr-set 219 0)
  (gr-set 128 0)
  (gr-set 178 0)
  (setq z-key (gr-num (or (gr-get 655) 90)))
  (setq gr-battle-script (list z-key))
  (setq gr-battle-script-index 0)
  (setq gr-battle-current-key 0)
  (setq gr-battle-turn-count 0)
  (setq gr-battle-frame-count 0)
  (setq gr-battle-error nil)
  (setq gr-sumi nil gr-trace nil gr-missing nil gr-step-count 0)
  (if (not (gr-battle-place-adjacent-enemy))
      (princ "BATTLE-GAPS no-enemy-generated\n")
    (princ (format "BATTLE-SEED enemy-slot=%s enemy-id=%s pos=%s,%s player=%s,%s dir=%s hp=%s\n"
                   gr-battle-enemy-index
                   (gr-prop-ref (aref (gr-get 83) gr-battle-enemy-index) "Var0")
                   (gr-prop-ref (aref (gr-get 83) gr-battle-enemy-index) "Var1")
                   (gr-prop-ref (aref (gr-get 83) gr-battle-enemy-index) "Var2")
                   (gr-get 66)
                   (gr-get 67)
                   (gr-get 199)
                   (gr-battle-enemy-hp)))
    (unwind-protect
        (progn
          (gr-battle-install-wrappers)
          (condition-case err
              (catch 'gr-battle-stop
                (gr-run-func "func009"))
            (error
             (setq gr-battle-error err))))
      (gr-battle-restore-wrappers))
    (princ (format "BATTLE-TRACE %s\n"
                   (mapconcat (lambda (id) (format "func%s" id))
                              (mapcar #'number-to-string (reverse gr-trace))
                              " ")))
    (when gr-missing
      (princ (format "BATTLE-MISSING %s\n" (delete-dups (reverse gr-missing)))))
    (when gr-battle-error
      (princ (format "BATTLE-ERROR %s\n" gr-battle-error)))
    (if (and (equal gr-battle-turn-count 1)
             (not (gr-battle-enemy-alive-p))
             (null gr-battle-error)
             (null gr-missing))
        (setq result "BATTLE-OK")
      (setq result "BATTLE-PARTIAL"))
    (princ (format "%s enemy-alive=%s enemy-hp=%s player-hp=%s\n"
                   result
                   (if (gr-battle-enemy-alive-p) 1 0)
                   (gr-battle-enemy-hp)
                   (gr-get 211)))))
