;;; run-menu.el --- in-game menu verification -*- coding: utf-8; -*-

(defvar gr-menu-orig-func080 nil)
(defvar gr-menu-orig-func009 nil)
(defvar gr-menu-script nil)
(defvar gr-menu-script-index 0)
(defvar gr-menu-current-key 0)
(defvar gr-menu-frame-count 0)
(defvar gr-menu-frame-limit 6)
(defvar gr-menu-error nil)

(defun gr-menu-set-cell (grid x y value)
  "Set GRID[X][Y] to VALUE when the coordinates are in range."
  (let ((row (and (vectorp grid) (gr-index-ref grid x))))
    (when (and (vectorp row) (>= y 0) (< y (length row)))
      (aset row y value))))

(defun gr-menu-read-key-state (keycode)
  "Return scripted key state for KEYCODE."
  (if (equal (gr-num keycode) gr-menu-current-key) 1 0))

(defun gr-menu-histogram ()
  "Return an alist mapping sumi op -> count."
  (let ((hist (make-hash-table :test 'equal)))
    (dolist (entry gr-sumi)
      (puthash (car entry)
               (1+ (gethash (car entry) hist 0))
               hist))
    (let ((pairs nil))
      (maphash (lambda (k v) (push (cons k v) pairs)) hist)
      (sort pairs (lambda (a b) (string< (car a) (car b)))))))

(defun gr-menu-format-histogram (hist)
  "Format HIST as op=count pairs."
  (mapconcat (lambda (pair) (format "%s=%s" (car pair) (cdr pair))) hist " "))

(defun gr-menu-histogram-delta (before after)
  "Return AFTER-BEFORE as an alist."
  (let ((table (make-hash-table :test 'equal))
        (pairs nil))
    (dolist (pair before)
      (puthash (car pair) (- (gethash (car pair) table 0) (cdr pair)) table))
    (dolist (pair after)
      (puthash (car pair) (+ (gethash (car pair) table 0) (cdr pair)) table))
    (maphash (lambda (k v)
               (when (/= v 0)
                 (push (cons k v) pairs)))
             table)
    (sort pairs (lambda (a b) (string< (car a) (car b))))))

(defun gr-menu-draw-texts ()
  "Return the ordered gui-draw-text payloads."
  (let ((out nil))
    (dolist (entry (reverse gr-sumi))
      (when (and (equal (car entry) "gui-draw-text")
                 (car (cdr entry)))
        (push (car (cdr entry)) out)))
    (nreverse out)))

(defun gr-menu-set-item-slot (slot item-id)
  "Seed one inventory SLOT with ITEM-ID."
  (let ((row (aref (gr-get 233) slot))
        (field 0))
    (while (< field (length row))
      (aset row field 0)
      (setq field (1+ field)))
    (gr-prop-set row "Var0" item-id)))

(defun gr-menu-expected-name (item-id)
  "Resolve ITEM-ID through func492 and return item_name."
  (gr-set "belongings_item_list" item-id)
  (gr-run-func "func492")
  (format "%s" (or (gr-get "item_name") "")))

(defun gr-menu-wrap-func080 (&rest args)
  "Feed one scripted key into func080."
  (setq gr-menu-current-key
        (if (< gr-menu-script-index (length gr-menu-script))
            (nth gr-menu-script-index gr-menu-script)
          0))
  (setq gr-menu-script-index (1+ gr-menu-script-index))
  (apply gr-menu-orig-func080 args))

(defun gr-menu-wrap-func009 (&rest args)
  "Stop when control returns to the field after the scripted menu path."
  (setq gr-menu-frame-count (1+ gr-menu-frame-count))
  (when (> gr-menu-frame-count gr-menu-frame-limit)
    (throw 'gr-menu-stop 'frame-limit))
  (when (and (> gr-menu-script-index (length gr-menu-script))
             (> gr-menu-frame-count 1))
    (throw 'gr-menu-stop 'done))
  (apply gr-menu-orig-func009 args))

(defun gr-menu-install-wrappers ()
  "Install scripted-input wrappers for the menu verification."
  (setq gr-menu-orig-func080 (gethash "func080" gr-native-funcs))
  (setq gr-menu-orig-func009 (gethash "func009" gr-native-funcs))
  (gr-defnative "func080" #'gr-menu-wrap-func080)
  (gr-defnative "func009" #'gr-menu-wrap-func009)
  (setq gr-read-key-state-fn #'gr-menu-read-key-state)
  (setq gr-reset-key-fn nil))

(defun gr-menu-restore-wrappers ()
  "Restore the original menu wrapper targets."
  (when gr-menu-orig-func080
    (gr-defnative "func080" gr-menu-orig-func080))
  (when gr-menu-orig-func009
    (gr-defnative "func009" gr-menu-orig-func009))
  (setq gr-read-key-state-fn nil)
  (setq gr-reset-key-fn nil))

(let* ((runtime-dir (file-name-directory (or load-file-name buffer-file-name)))
       (repo-root (expand-file-name ".." runtime-dir))
       (test-root (expand-file-name "build/menu-test-data" repo-root))
       (key-a 0)
       (key-down 0)
       (key-x 0)
       (base-hist nil)
       (menu-hist nil)
       (delta-hist nil)
       (item1 100)
       (item2 101)
       (name1 "")
       (name2 "")
       (texts nil)
       (result "MENU-PARTIAL"))
  (load-file (expand-file-name "game-runner.el" runtime-dir))
  (load-file (expand-file-name "gamedata-simple.el" runtime-dir))
  (load-file (expand-file-name "gamedata-conditional.el" runtime-dir))
  (setq gr-worldgen-autorun nil)
  (load-file (expand-file-name "run-worldgen.el" runtime-dir))
  (setq max-lisp-eval-depth 10000)
  (setq max-specpdl-size 10000)
  (make-directory test-root t)
  (let ((source-00 (expand-file-name "00.dat" gr-data-root))
        (target-00 (expand-file-name "00.dat" test-root)))
    (when (file-exists-p source-00)
      (copy-file source-00 target-00 t)))
  (setq gr-data-root (or (getenv "GR_DATA_ROOT") test-root))
  (gr-reset)
  (gr-set "stat" 1)
  (gr-set "hwnd" 0)
  (gr-run-func "func004")
  (gr-worldgen-seed-base-state)
  (gr-worldgen-run t)
  (gr-set 211 (max 15 (gr-num (or (gr-get 211) 0))))
  (gr-set 212 0)
  (gr-set 213 0)
  (gr-set 214 0)
  (gr-set 217 0)
  (gr-set 218 0)
  (gr-set 219 0)
  (gr-set 128 0)
  (gr-set 178 0)
  (gr-menu-set-item-slot 1 item1)
  (gr-menu-set-item-slot 2 item2)
  (gr-set 224 2)
  (gr-set 226 1)
  (gr-set "open_item_menue" 0)
  (when (and (gr-get 862) (gr-index-ref (gr-get 862) item1))
    (gr-menu-set-cell (gr-get 862) item1 0 1))
  (when (and (gr-get 862) (gr-index-ref (gr-get 862) item2))
    (gr-menu-set-cell (gr-get 862) item2 0 1))
  (setq name1 (gr-menu-expected-name item1))
  (setq name2 (gr-menu-expected-name item2))
  (setq key-a (gr-num (or (gr-get 657) 65)))
  (setq key-x (gr-num (or (gr-get 656) 88)))
  (setq key-down (gr-num (or (gr-get 650) 40)))
  (setq gr-sumi nil gr-trace nil gr-missing nil gr-step-count 0)
  (gr-run-func "func337")
  (setq base-hist (gr-menu-histogram))
  (setq gr-sumi nil gr-trace nil gr-missing nil gr-step-count 0)
  (setq gr-menu-script (list key-a key-a key-a key-down key-x))
  (setq gr-menu-script-index 0)
  (setq gr-menu-current-key 0)
  (setq gr-menu-frame-count 0)
  (setq gr-menu-error nil)
  (unwind-protect
      (progn
        (gr-menu-install-wrappers)
        (condition-case err
            (catch 'gr-menu-stop
              (gr-run-func "func009"))
          (error
           (setq gr-menu-error err))))
    (gr-menu-restore-wrappers))
  (setq menu-hist (gr-menu-histogram))
  (setq delta-hist (gr-menu-histogram-delta base-hist menu-hist))
  (setq texts (gr-menu-draw-texts))
  (princ (format "MENU-SEED items=%s,%s names=%S,%S\n" item1 item2 name1 name2))
  (princ (format "MENU-HIST-DELTA %s\n" (gr-menu-format-histogram delta-hist)))
  (princ (format "MENU-TEXTS %S\n" texts))
  (princ (format "MENU-TRACE %s\n"
                 (mapconcat (lambda (id) (format "func%s" id))
                            (mapcar #'number-to-string (reverse gr-trace))
                            " ")))
  (when gr-missing
    (princ (format "MENU-MISSING %s\n" (delete-dups (reverse gr-missing)))))
  (when gr-menu-error
    (princ (format "MENU-ERROR %s\n" gr-menu-error)))
  (if (and (member name1 texts)
           (member name2 texts)
           (null gr-menu-error)
           (null gr-missing))
      (setq result "MENU-OK")
    (setq result "MENU-PARTIAL"))
  (princ (format "%s names=%S,%S\n" result name1 name2)))
