;;; run-worldgen.el --- self-generated dungeon worldgen verification -*- coding: utf-8; -*-

(defconst gr-worldgen-build-dir
  (expand-file-name "../build" (file-name-directory (or load-file-name buffer-file-name))))

(defvar gr-worldgen-saved-func009 nil
  "Saved native func009 while world generation runs without entering the loop.")
(defvar gr-worldgen-saved-local-natives nil
  "Alist of native implementations overridden for worldgen verification.")
(defvar gr-worldgen-use-existing-state nil
  "When non-nil, reuse the current initialized state instead of seeding one.")
(defvar gr-worldgen-autorun t
  "When non-nil, execute the verification when this file is loaded.")

(defun gr-worldgen-with-loop-disabled (thunk)
  "Run THUNK with func009 temporarily replaced by a no-op."
  (setq gr-worldgen-saved-func009 (gethash "func009" gr-native-funcs))
  (unwind-protect
      (progn
        ;; func006 -> func007 -> func008 now reaches func009; worldgen only
        ;; needs the generated state, not the interactive loop.
        (gr-defnative "func009" (lambda (&rest _args) nil))
        (funcall thunk))
    (when gr-worldgen-saved-func009
      (gr-defnative "func009" gr-worldgen-saved-func009))
    (setq gr-worldgen-saved-func009 nil)))

(defun gr-worldgen-native-func250 (&rest _args)
  "Local corridor helper from func250."
  (let ((v76 (gr-get 76))
        (v71 (gr-get 71)))
    (push 250 gr-trace)
    (gr-set 1114 (gr-index-ref (gr-index-ref (gr-index-ref v76 (gr-get 1109)) 3) 1))
    (gr-set 1115 (gr-index-ref (gr-index-ref (gr-index-ref v76 (gr-get 1109)) 3) 2))
    (gr-set 1116 (gr-index-ref (gr-index-ref (gr-index-ref v76 (gr-get 1110)) 2) 1))
    (gr-set 1117 (gr-index-ref (gr-index-ref (gr-index-ref v76 (gr-get 1110)) 2) 2))
    (gr-set 1118 (gr-index-ref (gr-index-ref (gr-index-ref v76 (gr-get 1109)) 2) 1))
    (gr-set 1119 (gr-index-ref (gr-index-ref (gr-index-ref v76 (gr-get 1109)) 2) 2))
    (when (member (gr-get 1109) '(2 6 10))
      (when (equal (gr-index-ref (gr-get 493) (gr-get 1112)) 0)
        (let ((arr (gr-index-ref v71 (gr-get 1118))) (idx (gr-get 1119)))
          (when (and (vectorp arr) (integerp idx) (>= idx 0) (< idx (length arr)))
            (aset arr idx 0)))
        (let ((arr (gr-index-ref (gr-index-ref v76 (gr-get 1109)) 2)))
          (when (vectorp arr)
            (aset arr 1 0)
            (aset arr 2 0)))))
    (when (member (gr-get 1109) '(3 4 7 8 11 12))
      (when (and (equal (gr-index-ref (gr-get 493) (gr-get 1112)) 0)
                 (equal (gr-index-ref (gr-get 493) (gr-get 1113)) 0))
        (let ((arr (gr-index-ref v71 (gr-get 1118))) (idx (gr-get 1119)))
          (when (and (vectorp arr) (integerp idx) (>= idx 0) (< idx (length arr)))
            (aset arr idx 0)))
        (let ((arr (gr-index-ref (gr-index-ref v76 (gr-get 1109)) 2)))
          (when (vectorp arr)
            (aset arr 1 0)
            (aset arr 2 0)))))
    (when (and (not (equal (gr-get 1114) 0)) (not (equal (gr-get 1115) 0)))
      (unless (and (equal (gr-get 1110) (gr-get 95))
                   (not (equal (gr-get 1005) 1)))
        (when (or (equal (gr-get 1116) 0) (equal (gr-get 1117) 0))
          (gr-set 1116 (gr-index-ref (gr-index-ref (gr-index-ref v76 (gr-get 1111)) 2) 1))
          (gr-set 1117 (gr-index-ref (gr-index-ref (gr-index-ref v76 (gr-get 1111)) 2) 2)))
        (unless (or (equal (gr-get 1116) 0) (equal (gr-get 1117) 0))
          (gr-set 1120 (gr-get 1114))
          (gr-set 1121 (gr-get 1115))
          (gr-set 1122 (- (gr-num (gr-get 1116)) (gr-num (gr-get 1114)) 1))
          (gr-set 1123 (1+ (gr-random (gr-get 1122))))
          (let ((cnt1 0))
            (while (< cnt1 (gr-num (gr-get 1123)))
              (let ((arr (gr-index-ref v71 (gr-get 1120))) (idx (gr-get 1121)))
                (when (and (vectorp arr) (integerp idx) (>= idx 0) (< idx (length arr)))
                  (aset arr idx 14)))
              (gr-set 1120 (1+ (gr-num (gr-get 1120))))
              (setq cnt1 (1+ cnt1))))
          (cond
           ((equal (gr-get 1115) (gr-get 1117)) (gr-set 1124 0))
           ((> (gr-num (gr-get 1115)) (gr-num (gr-get 1117))) (gr-set 1124 1))
           (t (gr-set 1124 2)))
          (let ((cnt1 0))
            (while (< cnt1 10)
              (let ((arr (gr-index-ref v71 (gr-get 1120))) (idx (gr-get 1121)))
                (when (and (vectorp arr) (integerp idx) (>= idx 0) (< idx (length arr)))
                  (aset arr idx 14)))
              (when (equal (gr-get 1121) (gr-get 1117))
                (setq cnt1 10))
              (when (equal (gr-get 1124) 1)
                (gr-set 1121 (max 0 (1- (gr-num (gr-get 1121))))))
              (when (equal (gr-get 1124) 2)
                (gr-set 1121 (1+ (gr-num (gr-get 1121)))))
              (setq cnt1 (1+ cnt1))))
          (let ((cnt1 0))
            (while (< cnt1 30)
              (let ((arr (gr-index-ref v71 (gr-get 1120))) (idx (gr-get 1121)))
                (when (and (vectorp arr) (integerp idx) (>= idx 0) (< idx (length arr)))
                  (aset arr idx 14)))
              (when (equal (gr-get 1120) (gr-get 1116))
                (setq cnt1 30))
              (gr-set 1120 (1+ (gr-num (gr-get 1120))))
              (setq cnt1 (1+ cnt1)))))))))

(defun gr-worldgen-native-func251 (&rest _args)
  "Local corridor helper from func251."
  (let ((v76 (gr-get 76))
        (v71 (gr-get 71)))
    (push 251 gr-trace)
    (gr-set 1114 (gr-index-ref (gr-index-ref (gr-index-ref v76 (gr-get 1109)) 4) 1))
    (gr-set 1115 (gr-index-ref (gr-index-ref (gr-index-ref v76 (gr-get 1109)) 4) 2))
    (gr-set 1116 (gr-index-ref (gr-index-ref (gr-index-ref v76 (gr-get 1110)) 1) 1))
    (gr-set 1117 (gr-index-ref (gr-index-ref (gr-index-ref v76 (gr-get 1110)) 1) 2))
    (gr-set 1118 (gr-index-ref (gr-index-ref (gr-index-ref v76 (gr-get 1109)) 1) 1))
    (gr-set 1119 (gr-index-ref (gr-index-ref (gr-index-ref v76 (gr-get 1109)) 1) 2))
    (when (member (gr-get 1109) '(5 6 7 8))
      (when (equal (gr-index-ref (gr-get 493) (gr-get 1112)) 0)
        (let ((arr (gr-index-ref v71 (gr-get 1118))) (idx (gr-get 1119)))
          (when (and (vectorp arr) (integerp idx) (>= idx 0) (< idx (length arr)))
            (aset arr idx 0)))
        (let ((arr (gr-index-ref (gr-index-ref v76 (gr-get 1109)) 1)))
          (when (vectorp arr)
            (aset arr 1 0)
            (aset arr 2 0)))))
    (when (member (gr-get 1109) '(9 10 11 12))
      (when (and (equal (gr-index-ref (gr-get 493) (gr-get 1112)) 0)
                 (equal (gr-index-ref (gr-get 493) (gr-get 1113)) 0))
        (let ((arr (gr-index-ref v71 (gr-get 1118))) (idx (gr-get 1119)))
          (when (and (vectorp arr) (integerp idx) (>= idx 0) (< idx (length arr)))
            (aset arr idx 0)))
        (let ((arr (gr-index-ref (gr-index-ref v76 (gr-get 1109)) 1)))
          (when (vectorp arr)
            (aset arr 1 0)
            (aset arr 2 0)))))
    (when (and (not (equal (gr-get 1114) 0)) (not (equal (gr-get 1115) 0)))
      (unless (and (equal (gr-get 1110) (gr-get 95))
                   (not (equal (gr-get 1005) 3)))
        (when (or (equal (gr-get 1116) 0) (equal (gr-get 1117) 0))
          (gr-set 1116 (gr-index-ref (gr-index-ref (gr-index-ref v76 (gr-get 1111)) 1) 1))
          (gr-set 1117 (gr-index-ref (gr-index-ref (gr-index-ref v76 (gr-get 1111)) 1) 2)))
        (unless (or (equal (gr-get 1116) 0) (equal (gr-get 1117) 0))
          (gr-set 1120 (gr-get 1114))
          (gr-set 1121 (gr-get 1115))
          (gr-set 1125 (- (gr-num (gr-get 1117)) (gr-num (gr-get 1115)) 1))
          (gr-set 1126 (1+ (gr-random (gr-get 1125))))
          (let ((cnt1 0))
            (while (< cnt1 (gr-num (gr-get 1126)))
              (let ((arr (gr-index-ref v71 (gr-get 1120))) (idx (gr-get 1121)))
                (when (and (vectorp arr) (integerp idx) (>= idx 0) (< idx (length arr)))
                  (aset arr idx 14)))
              (gr-set 1121 (1+ (gr-num (gr-get 1121))))
              (setq cnt1 (1+ cnt1))))
          (cond
           ((equal (gr-get 1114) (gr-get 1116)) (gr-set 1124 0))
           ((> (gr-num (gr-get 1114)) (gr-num (gr-get 1116))) (gr-set 1124 1))
           (t (gr-set 1124 2)))
          (let ((cnt1 0))
            (while (< cnt1 10)
              (let ((arr (gr-index-ref v71 (gr-get 1120))) (idx (gr-get 1121)))
                (when (and (vectorp arr) (integerp idx) (>= idx 0) (< idx (length arr)))
                  (aset arr idx 14)))
              (when (equal (gr-get 1120) (gr-get 1116))
                (setq cnt1 10))
              (when (equal (gr-get 1124) 1)
                (gr-set 1120 (max 0 (1- (gr-num (gr-get 1120))))))
              (when (equal (gr-get 1124) 2)
                (gr-set 1120 (1+ (gr-num (gr-get 1120)))))
              (setq cnt1 (1+ cnt1))))
          (let ((cnt1 0))
            (while (< cnt1 30)
              (let ((arr (gr-index-ref v71 (gr-get 1120))) (idx (gr-get 1121)))
                (when (and (vectorp arr) (integerp idx) (>= idx 0) (< idx (length arr)))
                  (aset arr idx 14)))
              (when (equal (gr-get 1121) (gr-get 1117))
                (setq cnt1 30))
              (gr-set 1121 (1+ (gr-num (gr-get 1121))))
              (setq cnt1 (1+ cnt1)))))))))

(defun gr-worldgen-native-func252 (&rest _args)
  "Local cleanup helper from func252."
  (let ((v71 (gr-get 71))
        (y 1)
        (x 1))
    (push 252 gr-trace)
    (while (< y (gr-num (gr-get 32)))
      (setq x 1)
      (while (< x (gr-num (gr-get 31)))
        (when (equal (gr-index-ref (gr-index-ref v71 x) y) 14)
          (let ((left (max 0 (1- x)))
                (right (min (gr-num (gr-get 31)) (1+ x)))
                (up (max 0 (1- y)))
                (down (min (gr-num (gr-get 32)) (1+ y))))
            (when (and (not (equal (gr-index-ref (gr-index-ref v71 left) y) 14))
                       (not (equal (gr-index-ref (gr-index-ref v71 right) y) 14))
                       (not (equal (gr-index-ref (gr-index-ref v71 x) up) 14))
                       (not (equal (gr-index-ref (gr-index-ref v71 x) down) 14)))
              (let ((arr (gr-index-ref v71 x)))
                (when (and (vectorp arr) (>= y 0) (< y (length arr)))
                  (aset arr y 0))))))
        (setq x (1+ x)))
      (setq y (1+ y)))))

(defun gr-worldgen-native-func536 (&rest _args)
  "No-op placement helper for worldgen batch verification."
  (push 536 gr-trace)
  nil)

(defun gr-worldgen-native-func628 (&rest _args)
  "Minimal dungeon-1 enemy selector for worldgen batch verification."
  (push 628 gr-trace)
  (gr-set 953 1))

(defun gr-worldgen-native-func720 (&rest _args)
  "No-op cleanup helper for worldgen batch verification."
  (push 720 gr-trace)
  nil)

(defun gr-worldgen-native-func231 (&rest _args)
  "No-op save helper for worldgen batch verification."
  (push 231 gr-trace)
  nil)

(defun gr-worldgen-install-local-natives ()
  "Install local natives needed by the fixed worldgen path."
  (setq gr-worldgen-saved-local-natives nil)
  (dolist (name-fn '(("func250" . gr-worldgen-native-func250)
                     ("func251" . gr-worldgen-native-func251)
                     ("func252" . gr-worldgen-native-func252)
                     ("func536" . gr-worldgen-native-func536)
                     ("func628" . gr-worldgen-native-func628)
                     ("func720" . gr-worldgen-native-func720)
                     ("func231" . gr-worldgen-native-func231)))
    (push (cons (car name-fn) (gethash (car name-fn) gr-native-funcs))
          gr-worldgen-saved-local-natives)
    (gr-defnative (car name-fn) (symbol-function (cdr name-fn)))))

(defun gr-worldgen-restore-local-natives ()
  "Restore any natives replaced for worldgen verification."
  (dolist (entry gr-worldgen-saved-local-natives)
    (if (cdr entry)
        (gr-defnative (car entry) (cdr entry))
      (when gr-native-funcs
        (remhash (car entry) gr-native-funcs))))
  (setq gr-worldgen-saved-local-natives nil))

(defun gr-worldgen-count-map ()
  "Return (FLOOR WALLS) from var_71 over the active map rectangle."
  (let ((floor 0)
        (walls 0)
        (x 0)
        (y 0)
        (limit-x (gr-num (or (gr-get 31) 0)))
        (limit-y (gr-num (or (gr-get 32) 0)))
        (tiles (gr-get 71))
        (cell nil))
    (while (< y limit-y)
      (setq x 0)
      (while (< x limit-x)
        (setq cell (gr-index-ref (gr-index-ref tiles x) y))
        (when (and (numberp cell) (>= cell 1) (<= cell 12))
          (setq floor (1+ floor)))
        (when (equal cell 13)
          (setq walls (1+ walls)))
        (setq x (1+ x)))
      (setq y (1+ y)))
    (list floor walls)))

(defun gr-worldgen-count-records (slot)
  "Count nonzero Var0 entries in SLOT."
  (let ((rows (gr-get slot))
        (count 0)
        (i 0)
        (row nil))
    (when (vectorp rows)
      (while (< i (length rows))
        (setq row (aref rows i))
        (when (and row (not (equal (gr-prop-ref row "Var0") 0)) (not (equal (gr-prop-ref row "Var0") nil)))
          (setq count (1+ count)))
        (setq i (1+ i))))
    count))

(defun gr-worldgen-seed-base-state ()
  "Seed the minimum pre-worldgen state needed by func006/func007/func008."
  (gr-set 20 50)
  (gr-set 31 56)
  (gr-set 32 38)
  (gr-set 33 56)
  (gr-set 34 37)
  (gr-set 35 40)
  (gr-set 36 40)
  (gr-set 37 6)
  (gr-set 38 6)
  (gr-set 68 0)
  (gr-set 69 0)
  (gr-set 70 0)
  (gr-set 85 0)
  (gr-set 86 0)
  (gr-set 95 0)
  (gr-set 96 0)
  (gr-set 107 0)
  (gr-set 200 0)
  (gr-set 201 0)
  (gr-set 202 0)
  (gr-set 203 0)
  (gr-set 224 20)
  (gr-set 247 1)
  (gr-set 3121 0)
  (gr-set "special_floor" 0)
  (gr-set "dungeon_number" 1)
  (gr-set "current_floor" 1)
  (gr-set "dungeon1_floor" 1)
  (gr-set "dungeon2_floor" 0)
  (gr-set "dungeon3_floor" 0)
  (gr-set "time_paused" 0)
  (gr-set "time_paused_count" 0)
  (gr-set "count_buying_price" 0)
  (gr-set "y_axis_map_image" 0)
  (gr-set "open_item_menue" 0)
  (gr-set "taskact1_on" 0)
  (gr-set "equip_disc" (gr-make-array 500))
  (gr-set 493 (gr-make-array 20))
  (gr-set 704 (gr-make-array 300))
  (gr-set 25 (gr-make-array 30))
  (gr-set 26 (gr-make-array 30))
  (gr-set 27 (gr-make-array 30)))

(defun gr-worldgen-write-dump ()
  "Write the current func337 sumi stream for the self-generated state."
  (let* ((dump-path (expand-file-name "worldgen-sumi-dump.txt" gr-worldgen-build-dir))
         (json (if (fboundp 'gr-sumi-to-json)
                   (gr-sumi-to-json)
                 (prin1-to-string gr-sumi))))
    (make-directory gr-worldgen-build-dir t)
    (with-temp-file dump-path
      (insert json)
      (insert "\n")
      (insert (format "SUMI-DUMP-OK func337 %s\n" (length gr-sumi))))
    dump-path))

(defun gr-worldgen-run (&optional use-existing-state)
  "Run the worldgen verification.
When USE-EXISTING-STATE is non-nil, keep the caller's initialized state."
  (let ((old-budget gr-step-budget)
        (old-depth gr-depth-limit)
        (map-counts nil)
        (floor-cells 0)
        (walls 0)
        (enemies 0)
        (items 0)
        (ok nil)
        (dump-path nil))
    (unwind-protect
        (progn
          (unless use-existing-state
            (gr-reset)
            (gr-worldgen-seed-base-state))
          (gr-worldgen-install-local-natives)
          (setq gr-step-count 0)
          (setq gr-step-budget 500000)
          (setq gr-depth-limit 400)
          (gr-worldgen-with-loop-disabled
           (lambda ()
             (condition-case err
                 (gr-run-func "func006")
               (error
                (princ (format "WORLDGEN-ERROR %s\n" err))))))
          (setq map-counts (gr-worldgen-count-map))
          (setq floor-cells (nth 0 map-counts))
          (setq walls (nth 1 map-counts))
          (setq enemies (gr-worldgen-count-records 83))
          (setq items (gr-worldgen-count-records 78))
          (princ (format "WORLDGEN floor-cells=%s walls=%s\n" floor-cells walls))
          (princ (format "WORLDGEN dims=%s %s %s %s player=%s,%s dungeon=%s\n"
                         (or (gr-get 35) 0)
                         (or (gr-get 36) 0)
                         (or (gr-get 37) 0)
                         (or (gr-get 38) 0)
                         (or (gr-get 66) 0)
                         (or (gr-get 67) 0)
                         (or (gr-get "dungeon_number") 0)))
          (princ (format "WORLDGEN enemies=%s items=%s\n" enemies items))
          (setq ok (and (>= floor-cells 150)
                        (>= (gr-num (or (gr-get "dungeon_number") 0)) 1)))
          (princ (if ok "WORLDGEN-OK\n" "WORLDGEN-PARTIAL\n"))
          (when ok
            (setq gr-sumi nil gr-trace nil gr-missing nil)
            (setq gr-step-count 0)
            (condition-case err
                (gr-run-func "func337")
              (error
               (princ (format "WORLDGEN-RENDER-ERROR %s\n" err))))
            (setq dump-path (gr-worldgen-write-dump))
            (princ (format "WORLDGEN-DUMP %s\n" dump-path)))
          (when gr-missing
            (princ (format "WORLDGEN-MISSING %s\n" (reverse gr-missing)))))
      (setq gr-step-budget old-budget)
      (setq gr-depth-limit old-depth)
      (gr-worldgen-restore-local-natives))))

(when gr-worldgen-autorun
  (gr-worldgen-run gr-worldgen-use-existing-state))
