;;; run-saveload.el --- save/load round-trip verification -*- coding: utf-8; -*-

(let* ((runtime-dir (file-name-directory (or load-file-name buffer-file-name)))
       (repo-root (expand-file-name ".." runtime-dir))
       (test-root (expand-file-name "build/saves-test" repo-root))
       (save-file (expand-file-name "01.dat" test-root)))
  (load-file (expand-file-name "game-runner.el" runtime-dir))
  (load-file (expand-file-name "gamedata-simple.el" runtime-dir))
  (load-file (expand-file-name "gamedata-conditional.el" runtime-dir))
  (setq gr-worldgen-autorun nil)
  (load-file (expand-file-name "run-worldgen.el" runtime-dir))
  (setq max-lisp-eval-depth 10000)
  (setq max-specpdl-size 10000)
  (make-directory test-root t)
  (dolist (name '("00.dat" "01.dat" "01e.dat" "01n.dat" "02.dat" "02e.dat" "02n.dat" "03.dat" "03e.dat" "03n.dat"))
    (let ((path (expand-file-name name test-root)))
      (when (file-exists-p path)
        (delete-file path))))
  (let ((source-00 (expand-file-name "00.dat" gr-data-root))
        (target-00 (expand-file-name "00.dat" test-root)))
    (when (file-exists-p source-00)
      (copy-file source-00 target-00 t)))
  (setq gr-data-root test-root)
  (gr-reset)
  (gr-set "stat" 1)
  (gr-set "hwnd" 0)
  (gr-run-func "func004")
  (gr-worldgen-seed-base-state)
  (gr-worldgen-run t)
  (gr-set 726 1)
  (gr-set "wallet" 12345)
  (gr-set 66 12)
  (gr-set 67 9)
  (gr-run-func "func231")
  (princ (format "SAVELOAD-SAVED %s wallet=%s pos=%s,%s\n"
                 save-file
                 (gr-get "wallet")
                 (gr-get 66)
                 (gr-get 67)))
  (gr-reset)
  (setq gr-data-root test-root)
  (gr-set 726 1)
  (gr-run-func "func229")
  (princ (format "SAVELOAD-TRACE wallet=%s pos=%s,%s floor=%s dungeon=%s\n"
                 (gr-get "wallet")
                 (gr-get 66)
                 (gr-get 67)
                 (gr-get "current_floor")
                 (gr-get "dungeon_number")))
  (if (and (equal (gr-get "wallet") 12345)
           (equal (gr-get 66) 12)
           (equal (gr-get 67) 9))
      (princ "SAVELOAD-OK wallet=12345 pos=12,9\n")
    (princ "SAVELOAD-FAIL\n")))
