;;; run-tile-probe.el --- water-edge movement regression probe -*- coding: utf-8; -*-

(defun gr-tile-probe-tile-at (x y)
  "Return var_71[X][Y]."
  (gr-index-ref (gr-index-ref (gr-get 71) x) y))

(defun gr-tile-probe-floor-p (tile)
  "Return non-nil when TILE is a normal walkable floor."
  (and (numberp tile) (>= tile 1) (<= tile 12)))

(defun gr-tile-probe-adjacent-to-void-p (x y)
  "Return non-nil when X,Y touches at least one void tile."
  (let ((neighbors (list (list (1- x) y)
                         (list (1+ x) y)
                         (list x (1- y))
                         (list x (1+ y))))
        (found nil))
    (while (and neighbors (not found))
      (let* ((cell (car neighbors))
             (tile (gr-tile-probe-tile-at (nth 0 cell) (nth 1 cell))))
        (when (equal tile 0)
          (setq found t)))
      (setq neighbors (cdr neighbors)))
    found))

(defun gr-tile-probe-find-edge-path ()
  "Return (START-X START-Y DEST-X DEST-Y DIR VOID-X VOID-Y) for a floor edge walk."
  (let ((limit-x (gr-num (or (gr-get 31) 0)))
        (limit-y (gr-num (or (gr-get 32) 0)))
        (x 1)
        (y 1)
        (result nil))
    (while (and (< y (1- limit-y)) (null result))
      (setq x 1)
      (while (and (< x (1- limit-x)) (null result))
        (when (and (gr-tile-probe-floor-p (gr-tile-probe-tile-at x y))
                   (gr-tile-probe-adjacent-to-void-p x y))
          (dolist (candidate '((1 0 6) (-1 0 4) (0 1 2) (0 -1 8)))
            (let* ((dx (nth 0 candidate))
                   (dy (nth 1 candidate))
                   (dir (nth 2 candidate))
                   (nx (+ x dx))
                   (ny (+ y dy)))
              (when (and (null result)
                         (gr-tile-probe-floor-p (gr-tile-probe-tile-at nx ny))
                         (gr-tile-probe-adjacent-to-void-p nx ny))
                (setq result (list x y nx ny dir))))))
        (setq x (1+ x)))
      (setq y (1+ y)))
    result))

(defun gr-tile-probe-find-void-step (start-x start-y)
  "Return (START-X START-Y VOID-X VOID-Y DIR) for one direct void step."
  (let ((candidates '((1 0 6) (-1 0 4) (0 1 2) (0 -1 8)))
        (result nil))
    (while (and candidates (null result))
      (let* ((candidate (car candidates))
             (dx (nth 0 candidate))
             (dy (nth 1 candidate))
             (dir (nth 2 candidate))
             (nx (+ start-x dx))
             (ny (+ start-y dy)))
        (when (equal (gr-tile-probe-tile-at nx ny) 0)
          (setq result (list start-x start-y nx ny dir))))
      (setq candidates (cdr candidates)))
    result))

(defvar gr-tile-probe-func009-count 0)
(defvar gr-tile-probe-func019-count 0)
(defvar gr-tile-probe-orig-func009 nil)
(defvar gr-tile-probe-orig-func019 nil)
(defvar gr-tile-probe-orig-func080 nil)

(defun gr-tile-probe-wrap-func009 (&rest _args)
  "Count blocked/void fallbacks without entering the main loop."
  (setq gr-tile-probe-func009-count (1+ gr-tile-probe-func009-count))
  nil)

(defun gr-tile-probe-wrap-func019 (&rest _args)
  "Count successful turn handoffs without running enemy AI."
  (setq gr-tile-probe-func019-count (1+ gr-tile-probe-func019-count))
  nil)

(defun gr-tile-probe-wrap-func080 (&rest _args)
  "Keep key polling side-effect free."
  nil)

(defun gr-tile-probe-install-wrappers ()
  "Install local wrappers for the probe."
  (setq gr-tile-probe-orig-func009 (gethash "func009" gr-native-funcs))
  (setq gr-tile-probe-orig-func019 (gethash "func019" gr-native-funcs))
  (setq gr-tile-probe-orig-func080 (gethash "func080" gr-native-funcs))
  (gr-defnative "func009" #'gr-tile-probe-wrap-func009)
  (gr-defnative "func019" #'gr-tile-probe-wrap-func019)
  (gr-defnative "func080" #'gr-tile-probe-wrap-func080))

(defun gr-tile-probe-restore-wrappers ()
  "Restore wrappers replaced for the probe."
  (when gr-tile-probe-orig-func009
    (gr-defnative "func009" gr-tile-probe-orig-func009))
  (when gr-tile-probe-orig-func019
    (gr-defnative "func019" gr-tile-probe-orig-func019))
  (when gr-tile-probe-orig-func080
    (gr-defnative "func080" gr-tile-probe-orig-func080)))

(defun gr-tile-probe-run-move (start-x start-y dest-x dest-y dir)
  "Run func015 once from START-X,START-Y to DEST-X,DEST-Y in DIR."
  (setq gr-tile-probe-func009-count 0
        gr-tile-probe-func019-count 0)
  (gr-set 66 dest-x)
  (gr-set 67 dest-y)
  (gr-set 236 start-x)
  (gr-set 237 start-y)
  (gr-set 199 dir)
  (gr-set 125 0)
  (gr-set 126 0)
  (gr-set 128 0)
  (gr-set 159 0)
  (gr-set 178 0)
  (gr-set 213 0)
  (gr-set 214 0)
  (gr-set 217 0)
  (gr-set 218 0)
  (gr-set 219 0)
  (gr-set "key_X_on" 0)
  (gr-set 211 15)
  (gr-set 212 0)
  (gr-run-func "func015")
  (list :x (gr-get 66)
        :y (gr-get 67)
        :hp (gr-get 211)
        :blocked gr-tile-probe-func009-count
        :turn gr-tile-probe-func019-count))

(defun gr-tile-probe-set-cell (grid x y value)
  "Set GRID[X][Y] to VALUE when the coordinates are in range."
  (let ((row (and (vectorp grid) (gr-index-ref grid x))))
    (when (and (vectorp row) (>= y 0) (< y (length row)))
      (aset row y value))))

(defun gr-tile-probe-find-enemy-slot ()
  "Return the first live enemy slot."
  (let ((rows (gr-get 83))
        (idx 1)
        (found 0))
    (while (and (vectorp rows) (< idx (length rows)) (equal found 0))
      (when (and (not (equal (gr-prop-ref (aref rows idx) "Var0") 0))
                 (> (gr-num (or (gr-prop-ref (aref rows idx) "Var3") 0)) 0))
        (setq found idx))
      (setq idx (1+ idx)))
    found))

(defun gr-tile-probe-clear-other-enemies (keep-idx)
  "Zero every enemy row except KEEP-IDX and clear the occupancy map."
  (let ((rows (gr-get 83))
        (occ (gr-get 82))
        (idx 1)
        (row nil)
        (x 0)
        (y 0)
        (slot 0))
    (while (and (vectorp rows) (< idx (length rows)))
      (setq row (aref rows idx))
      (setq x (gr-num (or (gr-prop-ref row "Var1") 0)))
      (setq y (gr-num (or (gr-prop-ref row "Var2") 0)))
      (when (and (> x 0) (> y 0))
        (gr-tile-probe-set-cell occ x y 0))
      (unless (equal idx keep-idx)
        (setq slot 0)
        (while (< slot (length row))
          (aset row slot 0)
          (setq slot (1+ slot))))
      (setq idx (1+ idx)))
    (gr-set 97 1)))

(defun gr-tile-probe-find-enemy-placement (player-x player-y)
  "Return (EX EY) two tiles from PLAYER-X,PLAYER-Y on clear floor."
  (let ((candidates '((2 0) (-2 0) (0 2) (0 -2)))
        (found nil))
    (while (and candidates (null found))
      (let* ((candidate (car candidates))
             (dx (nth 0 candidate))
             (dy (nth 1 candidate))
             (mid-x (+ player-x (/ dx 2)))
             (mid-y (+ player-y (/ dy 2)))
             (enemy-x (+ player-x dx))
             (enemy-y (+ player-y dy)))
        (when (and (gr-tile-probe-floor-p (gr-tile-probe-tile-at mid-x mid-y))
                   (gr-tile-probe-floor-p (gr-tile-probe-tile-at enemy-x enemy-y))
                   (equal (gr-index-ref (gr-index-ref (gr-get 82) mid-x) mid-y) 0)
                   (equal (gr-index-ref (gr-index-ref (gr-get 82) enemy-x) enemy-y) 0))
          (setq found (list enemy-x enemy-y))))
      (setq candidates (cdr candidates)))
    found))

(defun gr-tile-probe-run-enemy-move (start-x start-y dest-x dest-y dir)
  "Run one real move and return enemy position before/after."
  (let* ((enemy-idx (gr-tile-probe-find-enemy-slot))
         (rows (gr-get 83))
         (occ (gr-get 82))
         (placement (gr-tile-probe-find-enemy-placement dest-x dest-y))
         (row nil)
         (before nil)
         (after nil))
    (unless (and (> enemy-idx 0) placement)
      (error "enemy probe could not place a test enemy"))
    (gr-tile-probe-clear-other-enemies enemy-idx)
    (setq row (aref rows enemy-idx))
    (gr-set 66 start-x)
    (gr-set 67 start-y)
    (gr-set 236 start-x)
    (gr-set 237 start-y)
    (gr-set 199 dir)
    (gr-set 125 0)
    (gr-set 126 0)
    (gr-set 128 0)
    (gr-set 159 0)
    (gr-set 178 0)
    (gr-set 213 0)
    (gr-set 214 0)
    (gr-set 217 0)
    (gr-set 218 0)
    (gr-set 219 0)
    (gr-set "key_X_on" 0)
    (gr-set 211 15)
    (gr-set 212 0)
    (gr-tile-probe-set-cell occ (gr-num (or (gr-prop-ref row "Var1") 0))
                            (gr-num (or (gr-prop-ref row "Var2") 0)) 0)
    (gr-prop-set row "Var1" (nth 0 placement))
    (gr-prop-set row "Var2" (nth 1 placement))
    (gr-prop-set row "Var3" 5)
    (gr-prop-set row "Var7" 0)
    (gr-prop-set row "Var8" 0)
    (gr-prop-set row "Var9" 0)
    (gr-prop-set row "Var12" 0)
    (gr-prop-set row "Var13" 0)
    (gr-prop-set row "Var15" 0)
    (gr-prop-set row "Var17" 0)
    (gr-prop-set row "Var18" 0)
    (gr-prop-set row "Var20" 0)
    (gr-tile-probe-set-cell occ (nth 0 placement) (nth 1 placement) enemy-idx)
    (setq before (list (gr-prop-ref row "Var1") (gr-prop-ref row "Var2")))
    (let ((saved-func009 (gethash "func009" gr-native-funcs))
          (saved-func080 (gethash "func080" gr-native-funcs)))
      (unwind-protect
          (progn
            (setq gr-trace nil)
            (gr-defnative "func009" #'gr-tile-probe-wrap-func009)
            (gr-defnative "func080" #'gr-tile-probe-wrap-func080)
            (gr-run-func "func015"))
        (when saved-func009
          (gr-defnative "func009" saved-func009))
        (when saved-func080
          (gr-defnative "func080" saved-func080))))
    (setq after (list (gr-prop-ref row "Var1") (gr-prop-ref row "Var2")))
    (list :before before :after after :slot enemy-idx :trace (reverse gr-trace))))

(let* ((runtime-dir (file-name-directory (or load-file-name buffer-file-name)))
       (repo-root (expand-file-name ".." runtime-dir))
       (test-root (expand-file-name "build/tile-probe-data" repo-root))
       (path nil)
       (walk nil)
       (void-step nil)
       (blocked nil)
       (enemy-move nil))
  (load-file (expand-file-name "game-runner.el" runtime-dir))
  (load-file (expand-file-name "gamedata-simple.el" runtime-dir))
  (load-file (expand-file-name "gamedata-conditional.el" runtime-dir))
  (setq gr-worldgen-autorun nil)
  (load-file (expand-file-name "run-worldgen.el" runtime-dir))
  (make-directory test-root t)
  (let ((source-00 (expand-file-name "00.dat" gr-data-root))
        (target-00 (expand-file-name "00.dat" test-root)))
    (when (file-exists-p source-00)
      (copy-file source-00 target-00 t)))
  (setq gr-data-root (or (getenv "GR_DATA_ROOT") test-root))
  (setq max-lisp-eval-depth 200000)
  (setq max-specpdl-size 200000)
  (setq gr-depth-limit 5000)
  (setq gr-step-budget 2000000)
  (gr-reset)
  (gr-set "stat" 1)
  (gr-set "hwnd" 0)
  (let ((saved-func139A (gethash "func139A" gr-native-funcs)))
    (unwind-protect
        (progn
          (gr-defnative "func139A" (lambda (&rest _args) nil))
          (gr-run-func "func004"))
      (if saved-func139A
          (gr-defnative "func139A" saved-func139A)
        (when gr-native-funcs
          (remhash "func139A" gr-native-funcs)))))
  (gr-worldgen-seed-base-state)
  (gr-worldgen-run t)
  (setq path (gr-tile-probe-find-edge-path))
  (unless path
    (error "tile probe could not find a floor edge path"))
  (setq void-step (gr-tile-probe-find-void-step (nth 0 path) (nth 1 path)))
  (unless void-step
    (error "tile probe could not find an adjacent void step"))
  (gr-tile-probe-install-wrappers)
  (unwind-protect
      (progn
        (setq walk (gr-tile-probe-run-move (nth 0 path) (nth 1 path) (nth 2 path) (nth 3 path) (nth 4 path)))
        (setq blocked (gr-tile-probe-run-move (nth 0 void-step) (nth 1 void-step)
                                              (nth 2 void-step) (nth 3 void-step) (nth 4 void-step)))
        (gr-tile-probe-restore-wrappers)
        (setq enemy-move (gr-tile-probe-run-enemy-move (nth 0 path) (nth 1 path) (nth 2 path) (nth 3 path) (nth 4 path)))
        (gr-tile-probe-install-wrappers)
        (princ (format "TILE-PROBE-PATH start=%s,%s dest=%s,%s dir=%s\n"
                       (nth 0 path) (nth 1 path) (nth 2 path) (nth 3 path) (nth 4 path)))
        (princ (format "TILE-PROBE-WALK %S\n" walk))
        (princ (format "TILE-PROBE-BLOCK %S\n" blocked))
        (princ (format "ENEMY-PROBE %S\n" enemy-move))
        ;; Tile and enemy verdicts are separate concerns: the tile fix is
        ;; deterministic, while enemy turns depend on the (still under
        ;; investigation) func019 -> func020 handoff and the layout.
        (if (and (= (gr-num (plist-get walk :x)) (nth 2 path))
                 (= (gr-num (plist-get walk :y)) (nth 3 path))
                 (= (gr-num (or (plist-get walk :hp) 0)) 15)
                 (= (or (plist-get walk :blocked) 0) 0)
                 (= (or (plist-get walk :turn) 0) 1)
                 (= (gr-num (plist-get blocked :x)) (nth 0 void-step))
                 (= (gr-num (plist-get blocked :y)) (nth 1 void-step))
                 (> (or (plist-get blocked :blocked) 0) 0))
            (princ "TILE-PROBE-OK\n")
          (princ "TILE-PROBE-FAIL\n"))
        (if (not (equal (plist-get enemy-move :before) (plist-get enemy-move :after)))
            (princ "ENEMY-PROBE-OK\n")
          (princ "ENEMY-PROBE-FAIL\n")))
    (gr-tile-probe-restore-wrappers)))
