;;; run-worldgen.el --- self-generated dungeon worldgen verification -*- coding: utf-8; -*-

(defconst gr-worldgen-build-dir
  (expand-file-name "../build" (file-name-directory (or load-file-name buffer-file-name))))

(defun gr-worldgen-count-map ()
  "Return (FLOOR WALLS) from var_71 over the active map rectangle."
  (let ((floor 0)
        (walls 0)
        (x 0)
        (y 0)
        (limit-x (gr-num (or (gr-get 31) 0)))
        (limit-y (gr-num (or (gr-get 32) 0)))
        (tiles (gr-get 71))
        (cell nil))
    (while (< y limit-y)
      (setq x 0)
      (while (< x limit-x)
        (setq cell (gr-index-ref (gr-index-ref tiles x) y))
        (when (and (numberp cell) (>= cell 1) (<= cell 12))
          (setq floor (1+ floor)))
        (when (equal cell 13)
          (setq walls (1+ walls)))
        (setq x (1+ x)))
      (setq y (1+ y)))
    (list floor walls)))

(defun gr-worldgen-count-records (slot)
  "Count nonzero Var0 entries in SLOT."
  (let ((rows (gr-get slot))
        (count 0)
        (i 0)
        (row nil))
    (when (vectorp rows)
      (while (< i (length rows))
        (setq row (aref rows i))
        (when (and row (not (equal (gr-prop-ref row "Var0") 0)) (not (equal (gr-prop-ref row "Var0") nil)))
          (setq count (1+ count)))
        (setq i (1+ i))))
    count))

(defun gr-worldgen-seed-base-state ()
  "Seed the minimum pre-worldgen state needed by func006/func007/func008."
  (gr-set 20 50)
  (gr-set 31 56)
  (gr-set 32 38)
  (gr-set 33 56)
  (gr-set 34 37)
  (gr-set 35 40)
  (gr-set 36 40)
  (gr-set 37 6)
  (gr-set 38 6)
  (gr-set 68 0)
  (gr-set 69 0)
  (gr-set 70 0)
  (gr-set 85 0)
  (gr-set 86 0)
  (gr-set 95 0)
  (gr-set 96 0)
  (gr-set 107 0)
  (gr-set 200 0)
  (gr-set 201 0)
  (gr-set 202 0)
  (gr-set 203 0)
  (gr-set 224 20)
  (gr-set 247 1)
  (gr-set 3121 0)
  (gr-set "special_floor" 0)
  (gr-set "dungeon_number" 1)
  (gr-set "current_floor" 1)
  (gr-set "dungeon1_floor" 1)
  (gr-set "dungeon2_floor" 0)
  (gr-set "dungeon3_floor" 0)
  (gr-set "time_paused" 0)
  (gr-set "time_paused_count" 0)
  (gr-set "count_buying_price" 0)
  (gr-set "y_axis_map_image" 0)
  (gr-set "open_item_menue" 0)
  (gr-set "taskact1_on" 0)
  (gr-set "equip_disc" (gr-make-array 500))
  (gr-set 493 (gr-make-array 20))
  (gr-set 704 (gr-make-array 300))
  (gr-set 25 (gr-make-array 30))
  (gr-set 26 (gr-make-array 30))
  (gr-set 27 (gr-make-array 30)))

(defun gr-worldgen-write-dump ()
  "Write the current func337 sumi stream for the self-generated state."
  (let* ((dump-path (expand-file-name "worldgen-sumi-dump.txt" gr-worldgen-build-dir))
         (json (gr-sumi-to-json)))
    (make-directory gr-worldgen-build-dir t)
    (with-temp-file dump-path
      (insert json)
      (insert "\n")
      (insert (format "SUMI-DUMP-OK func337 %s\n" (length gr-sumi))))
    dump-path))

(let ((old-budget gr-step-budget)
      (old-depth gr-depth-limit)
      (map-counts nil)
      (floor-cells 0)
      (walls 0)
      (enemies 0)
      (items 0)
      (ok nil)
      (dump-path nil))
  (unwind-protect
      (progn
        (gr-reset)
        (gr-worldgen-seed-base-state)
        (setq gr-step-count 0)
        (setq gr-step-budget 500000)
        (setq gr-depth-limit 400)
        (condition-case err
            (gr-run-func "func006")
          (error
           (princ (format "WORLDGEN-ERROR %s\n" err))))
        (setq map-counts (gr-worldgen-count-map))
        (setq floor-cells (nth 0 map-counts))
        (setq walls (nth 1 map-counts))
        (setq enemies (gr-worldgen-count-records 83))
        (setq items (gr-worldgen-count-records 78))
        (princ (format "WORLDGEN floor-cells=%s walls=%s\n" floor-cells walls))
        (princ (format "WORLDGEN dims=%s %s %s %s player=%s,%s dungeon=%s\n"
                       (or (gr-get 35) 0)
                       (or (gr-get 36) 0)
                       (or (gr-get 37) 0)
                       (or (gr-get 38) 0)
                       (or (gr-get 66) 0)
                       (or (gr-get 67) 0)
                       (or (gr-get "dungeon_number") 0)))
        (princ (format "WORLDGEN enemies=%s items=%s\n" enemies items))
        (setq ok (and (>= floor-cells 150)
                      (>= (gr-num (or (gr-get "dungeon_number") 0)) 1)))
        (princ (if ok "WORLDGEN-OK\n" "WORLDGEN-PARTIAL\n"))
        (when ok
          (setq gr-sumi nil gr-trace nil gr-missing nil)
          (setq gr-step-count 0)
          (condition-case err
              (gr-run-func "func337")
            (error
             (princ (format "WORLDGEN-RENDER-ERROR %s\n" err))))
          (setq dump-path (gr-worldgen-write-dump))
          (princ (format "WORLDGEN-DUMP %s\n" dump-path)))
        (when gr-missing
          (princ (format "WORLDGEN-MISSING %s\n" (reverse gr-missing)))))
    (setq gr-step-budget old-budget)
    (setq gr-depth-limit old-depth)))
