;;; scan-missing.el --- scan registered funcs for missing calls -*- coding: utf-8; -*-

(let ((names nil)
      (seen (make-hash-table :test 'equal))
      (missing-seen (make-hash-table :test 'equal))
      (errors nil)
      (missing-list nil))
  (maphash (lambda (name _value)
             (unless (gethash name seen)
               (puthash name t seen)
               (setq names (cons name names))))
           gr-funcs)
  (maphash (lambda (name _value)
             (unless (gethash name seen)
               (puthash name t seen)
               (setq names (cons name names))))
           gr-native-funcs)
  (setq names (sort names 'string<))
  (setq gr-step-budget 200000)
  (setq gr-depth-limit 200)
  (dolist (name names)
    (gr-reset)
    (setq gr-step-count 0)
    (condition-case err
        (gr-run-func name)
      (error
       (setq errors
             (cons (cons name (format "%s" err)) errors))))
    (dolist (miss gr-missing)
      (unless (gethash miss missing-seen)
        (puthash miss t missing-seen))))
  (setq gr-step-budget nil)
  (setq gr-depth-limit 400)
  (maphash (lambda (name _value)
             (setq missing-list (cons name missing-list)))
           missing-seen)
  (setq missing-list (sort missing-list 'string<))
  (setq errors
        (sort errors
              (lambda (a b)
                (string< (car a) (car b)))))
  (princ (format "MISSING-DISTINCT %s\n" (length missing-list)))
  (dolist (name missing-list)
    (princ (format "  MISS %s\n" name)))
  (princ (format "ERR-FUNCS %s\n" (length errors)))
  (dolist (entry errors)
    (princ (format "  ERR %s : %s\n" (car entry) (cdr entry))))
  (princ "SCAN-OK\n"))
