;;; sumi-survey.el --- survey drawable gr-sumi output -*- coding: utf-8; -*-

(defun gr-drawable-op-p (op)
  "Non-nil if OP counts as drawable output."
  (or (gr-string-prefix-p "gui-" op)
      (gr-string-prefix-p "dtw-draw" op)
      (equal op "dtw-play-sound")))

(let ((names nil)
      (seen (make-hash-table :test 'equal))
      (hist (make-hash-table :test 'equal))
      (drawers nil)
      (old-budget gr-step-budget)
      (old-depth gr-depth-limit)
      (name nil)
      (drawable 0)
      (entry nil)
      (op nil)
      (hist-list nil)
      (top nil)
      (limit 0))
  (maphash (lambda (name _value)
             (unless (gethash name seen)
               (puthash name t seen)
               (setq names (cons name names))))
           gr-funcs)
  (maphash (lambda (name _value)
             (unless (gethash name seen)
               (puthash name t seen)
               (setq names (cons name names))))
           gr-native-funcs)
  (setq names (sort names 'string<))
  (unwind-protect
      (progn
        (setq gr-step-budget 200000)
        (setq gr-depth-limit 200)
        (dolist (name names)
          (gr-reset)
          (setq gr-step-count 0)
          (condition-case _err
              (gr-run-func name)
            (error nil))
          (setq drawable 0)
          (dolist (entry gr-sumi)
            (setq op (car entry))
            (puthash op (1+ (or (gethash op hist) 0)) hist)
            (when (gr-drawable-op-p op)
              (setq drawable (1+ drawable))))
          (when (> drawable 0)
            (setq drawers (cons (cons name drawable) drawers)))))
    (setq gr-step-budget old-budget)
    (setq gr-depth-limit old-depth))
  (setq top
        (sort drawers
              (lambda (a b)
                (if (= (cdr a) (cdr b))
                    (string< (car a) (car b))
                  (> (cdr a) (cdr b))))))
  (maphash (lambda (op count)
             (setq hist-list (cons (cons op count) hist-list)))
           hist)
  (setq hist-list
        (sort hist-list
              (lambda (a b)
                (if (= (cdr a) (cdr b))
                    (string< (car a) (car b))
                  (> (cdr a) (cdr b))))))
  (princ "TOP-DRAWERS\n")
  (dolist (entry top)
    (when (< limit 20)
      (princ (format "  %s %s\n" (cdr entry) (car entry)))
      (setq limit (1+ limit))))
  (princ "OP-HISTOGRAM\n")
  (dolist (entry hist-list)
    (princ (format "  %s %s\n" (cdr entry) (car entry))))
  (princ "SURVEY-OK\n"))
