#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const ts = require("typescript");

const repoRoot = path.resolve(__dirname, "..");
const functionCatalogPath = path.join(repoRoot, "build", "function-catalog.json");

if (require.main === module) {
  main();
}

function main() {
  const args = process.argv.slice(2);
  const srcRoot = path.resolve(
    valueAfter(args, "--src-root") || path.join(repoRoot, "src", "renderer")
  );
  const outPath = path.resolve(
    valueAfter(args, "--out") || path.join(repoRoot, "nelisp_runtime", "gamedata-conditional.el")
  );
  let names = valuesAfter(args, "--name");
  const namesFile = valueAfter(args, "--names-file");
  if (namesFile) {
    names = names.concat(
      fs.readFileSync(path.resolve(namesFile), "utf8").split(/\s+/).filter(Boolean)
    );
  }
  if (!fs.existsSync(srcRoot)) throw new Error(`--src-root missing or not found: ${srcRoot}`);
  if (names.length === 0) throw new Error("pass at least one --name funcNNN/itemNNN or --names-file");

  const fileIndex = buildDefinitionIndex(srcRoot);
  const catalogIndex = buildCatalogIndex();
  const translated = [];
  const skipped = [];
  const noSource = [];
  for (const name of dedupe(names).sort(byFuncNumber)) {
    const sourceInfo = findSourceFile(catalogIndex, fileIndex, name);
    if (!sourceInfo) {
      noSource.push(name);
      continue;
    }
    try {
      translated.push({
        name,
        ...transpileFunc(name, sourceInfo),
      });
    } catch (error) {
      skipped.push([name, error.message]);
    }
  }

  const output = [
    ";;; gamedata-conditional.el --- generated native conditional funcs for NeLisp -*- coding: utf-8; lexical-binding: t; -*-",
    ";; Generated by tools/generate_nelisp_conditional_runtime.js using build/function-catalog.json.",
    ";; Do not edit by hand.",
    "",
    ...translated.flatMap(({ name, helpers, body }) => [
      ...(helpers || []).flatMap((helper) => [
        `(defun ${helper.elispName} (${helper.params.join(" ")})`,
        helper.body.map((line) => `  ${line}`).join("\n"),
        ")",
        "",
      ]),
      `(defun gr-native-${name} (&rest _args)`,
      body.map((line) => `  ${line}`).join("\n"),
      ")",
      "",
      ...runtimeAliases(name).flatMap((alias) => [
        `(gr-defnative "${alias}" #'gr-native-${name})`,
        "",
      ]),
    ]),
    "(provide 'gamedata-conditional)",
    "",
  ].join("\n");

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, output, "utf8");
  console.log(JSON.stringify({
    out: path.relative(repoRoot, outPath),
    translated: translated.map((entry) => entry.name),
    skipped,
    noSource,
  }, null, 2));
}

function valueAfter(args, flag) {
  const index = args.indexOf(flag);
  return index >= 0 ? args[index + 1] : null;
}

function valuesAfter(args, flag) {
  const out = [];
  for (let i = 0; i < args.length; i++) {
    if (args[i] === flag) out.push(args[i + 1]);
  }
  return out;
}

function dedupe(values) {
  return [...new Set(values)];
}

function byFuncNumber(a, b) {
  const na = Number(a.replace(/\D/g, ""));
  const nb = Number(b.replace(/\D/g, ""));
  return na - nb || a.localeCompare(b);
}

function canonicalFuncAlias(name) {
  const match = /^func(\d+)$/.exec(name);
  if (!match) return null;
  const digits = match[1].replace(/^0+/, "");
  if (!digits) return null;
  const canonical = `func${digits.padStart(3, "0")}`;
  return canonical !== name ? canonical : null;
}

function runtimeAliases(name) {
  return dedupe([name, canonicalFuncAlias(name)].filter(Boolean));
}

function isRuntimeName(name) {
  return /^(?:func[\dA-Za-z]+|item[\dA-Za-z]+)$/i.test(name);
}

function buildDefinitionIndex(root) {
  const files = [];
  walk(root, files);
  const defs = new Map();
  for (const file of files.filter((entry) => entry.endsWith(".ts"))) {
    const source = fs.readFileSync(file, "utf8");
    const sf = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
    for (const stmt of sf.statements) {
      if (ts.isFunctionDeclaration(stmt) && stmt.name && isRuntimeName(stmt.name.text)) {
        if (!defs.has(stmt.name.text)) defs.set(stmt.name.text, { file, sourceName: stmt.name.text });
      }
      if (ts.isExportDeclaration(stmt) && stmt.moduleSpecifier && stmt.exportClause && ts.isNamedExports(stmt.exportClause)) {
        const targetPath = resolveModuleFile(file, stmt.moduleSpecifier.text);
        if (!targetPath) continue;
        for (const element of stmt.exportClause.elements) {
          const exportedName = element.name.text;
          const localName = element.propertyName ? element.propertyName.text : exportedName;
          if (!isRuntimeName(exportedName) || !isRuntimeName(localName)) continue;
          if (!defs.has(exportedName)) defs.set(exportedName, { file: targetPath, sourceName: localName });
        }
      }
    }
  }
  return defs;
}

function buildCatalogIndex() {
  if (!fs.existsSync(functionCatalogPath)) return new Map();
  const catalog = JSON.parse(fs.readFileSync(functionCatalogPath, "utf8"));
  const defs = new Map();
  for (const entry of catalog.functions || []) {
    if (!entry || !entry.name || !entry.file) continue;
    if (!isRuntimeName(entry.name)) continue;
    defs.set(entry.name, {
      file: path.resolve(repoRoot, entry.file),
      sourceName: entry.name,
    });
  }
  return defs;
}

function resolveModuleFile(fromFile, specifier) {
  if (!specifier.startsWith(".")) return null;
  const base = path.resolve(path.dirname(fromFile), specifier);
  const candidates = [
    `${base}.ts`,
    path.join(base, "index.ts"),
  ];
  for (const candidate of candidates) {
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

function walk(dir, out) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else out.push(full);
  }
}

function findSourceFile(catalogDefs, fallbackDefs, name) {
  const canonical = canonicalFuncAlias(name);
  return catalogDefs.get(name)
    || fallbackDefs.get(name)
    || (canonical && (catalogDefs.get(canonical) || fallbackDefs.get(canonical))
      ? { ...(catalogDefs.get(canonical) || fallbackDefs.get(canonical)), sourceName: canonical }
      : null);
}

function transpileFunc(name, sourceInfo) {
  const file = sourceInfo.file;
  const source = fs.readFileSync(file, "utf8");
  const sf = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const sourceNames = dedupe([sourceInfo.sourceName, canonicalFuncAlias(sourceInfo.sourceName)].filter(Boolean));
  const func = sf.statements.find((stmt) =>
    ts.isFunctionDeclaration(stmt)
    && stmt.name
    && sourceNames.includes(stmt.name.text));
  if (!func || !func.body) throw new Error(`function ${name} not found`);

  const helperDecls = new Map();
  const fileConsts = new Map();
  for (const stmt of sf.statements) {
    if (ts.isFunctionDeclaration(stmt) && stmt.name && !sourceNames.includes(stmt.name.text)) {
      helperDecls.set(stmt.name.text, stmt);
      continue;
    }
    if (ts.isVariableStatement(stmt)) {
      for (const decl of stmt.declarationList.declarations) {
        if (ts.isIdentifier(decl.name) && decl.initializer) {
          fileConsts.set(decl.name.text, decl.initializer);
        }
      }
    }
  }

  const bodyStatements = func.body.statements.filter((stmt) => !isGeneratedGuard(stmt));
  if (bodyStatements.length === 0) throw new Error(`${name}: empty function body`);

  const locals = collectLocals(func.body);
  const helperNames = new Map([...helperDecls.keys()].map((helperName) => [
    helperName,
    `gr-native-${name}--${helperName}`,
  ]));
  const ctx = { name, sf, locals, helperDecls, helperNames, fileConsts };
  const helpers = [...helperDecls.entries()].map(([helperName, decl]) =>
    transpileHelper(name, helperName, decl, ctx));
  const lines = [];
  lines.push(`"${name}: transpiled from TypeScript conditional fallback."`);
  lines.push("(catch 'gr-return");
  if (locals.length) {
    lines.push(`  (let (${locals.map((name) => `(${name} nil)`).join(" ")})`);
    for (const stmt of bodyStatements) {
      emitStatement(stmt, lines, 2, ctx);
    }
    lines.push("  )");
  } else {
    for (const stmt of bodyStatements) {
      emitStatement(stmt, lines, 1, ctx);
    }
  }
  lines.push(")");
  return { helpers, body: lines };
}

function transpileHelper(parentName, helperName, decl, parentCtx) {
  if (!decl.body) throw new Error(`${parentName}: helper ${helperName} missing body`);
  const params = decl.parameters.map((param) => {
    if (!ts.isIdentifier(param.name)) throw unsupported(param, parentCtx, "helper destructuring parameter");
    return param.name.text;
  });
  const locals = collectLocals(decl.body);
  const bindingLocals = locals.filter((name) => !params.includes(name));
  const ctx = {
    ...parentCtx,
    name: `${parentName}/${helperName}`,
    locals,
  };
  const bodyStatements = decl.body.statements.filter((stmt) => !isGeneratedGuard(stmt));
  const lines = [];
  lines.push(`"${parentName}/${helperName}: transpiled local helper."`);
  lines.push("(catch 'gr-return");
  if (bindingLocals.length) {
    lines.push(`  (let (${bindingLocals.map((name) => `(${name} nil)`).join(" ")})`);
    for (const stmt of bodyStatements) {
      emitStatement(stmt, lines, 2, ctx);
    }
    lines.push("    nil");
    lines.push("  )");
  } else {
    for (const stmt of bodyStatements) {
      emitStatement(stmt, lines, 1, ctx);
    }
    lines.push("  nil");
  }
  lines.push(")");
  return {
    elispName: parentCtx.helperNames.get(helperName),
    params,
    body: lines,
  };
}

function collectLocals(node) {
  const locals = new Set();
  if (node.parent && ts.isFunctionDeclaration(node.parent)) {
    for (const param of node.parent.parameters) {
      if (ts.isIdentifier(param.name)) locals.add(param.name.text);
    }
  }
  function visit(current) {
    if (ts.isVariableDeclaration(current) && ts.isIdentifier(current.name)) {
      locals.add(current.name.text);
    }
    if (ts.isForStatement(current) && current.initializer && ts.isVariableDeclarationList(current.initializer)) {
      for (const decl of current.initializer.declarations) {
        if (ts.isIdentifier(decl.name)) locals.add(decl.name.text);
      }
    }
    ts.forEachChild(current, visit);
  }
  visit(node);
  return [...locals].sort();
}

function isGeneratedGuard(stmt) {
  if (!ts.isIfStatement(stmt)) return false;
  const cond = stmt.expression;
  if (!ts.isCallExpression(cond)) return false;
  if (!ts.isIdentifier(cond.expression) || cond.expression.text !== "shouldUseGeneratedGameFunction") return false;
  if (cond.arguments.length !== 1 || !ts.isStringLiteral(cond.arguments[0])) return false;
  if (!stmt.thenStatement || !ts.isBlock(stmt.thenStatement)) return false;
  const inner = stmt.thenStatement.statements;
  if (inner.length !== 2) return false;
  return ts.isExpressionStatement(inner[0]) && ts.isReturnStatement(inner[1]);
}

function emitStatement(stmt, lines, level, ctx) {
  if (ts.isBlock(stmt)) {
    for (const inner of stmt.statements) emitStatement(inner, lines, level, ctx);
    return;
  }
  if (ts.isExpressionStatement(stmt)) {
    emitExpressionStatement(stmt.expression, lines, level, ctx);
    return;
  }
  if (ts.isVariableStatement(stmt)) {
    emitVariableStatement(stmt, lines, level, ctx);
    return;
  }
  if (ts.isWhileStatement(stmt)) {
    emitWhile(stmt, lines, level, ctx);
    return;
  }
  if (ts.isForStatement(stmt)) {
    emitFor(stmt, lines, level, ctx);
    return;
  }
  if (ts.isIfStatement(stmt)) {
    emitIf(stmt, lines, level, ctx);
    return;
  }
  if (ts.isReturnStatement(stmt)) {
    lines.push(`${indent(level)}(throw 'gr-return ${stmt.expression ? emitValue(stmt.expression, ctx) : "nil"})`);
    return;
  }
  if (ts.isBreakStatement(stmt)) {
    lines.push(`${indent(level)}(throw 'gr-break nil)`);
    return;
  }
  if (ts.isContinueStatement(stmt)) {
    lines.push(`${indent(level)}(throw 'gr-continue nil)`);
    return;
  }
  throw unsupported(stmt, ctx, ts.SyntaxKind[stmt.kind]);
}

function emitVariableStatement(stmt, lines, level, ctx) {
  for (const decl of stmt.declarationList.declarations) {
    if (!ts.isIdentifier(decl.name)) throw unsupported(decl, ctx, "destructuring declaration");
    const init = decl.initializer ? emitValue(decl.initializer, ctx) : "nil";
    lines.push(`${indent(level)}(setq ${decl.name.text} ${init})`);
  }
}

function emitExpressionStatement(expr, lines, level, ctx) {
  if (ts.isCallExpression(expr) && isForEachCall(expr)) {
    emitForEach(expr, lines, level, ctx);
    return;
  }
  if (ts.isCallExpression(expr) && isPushCall(expr)) {
    emitPush(expr, lines, level, ctx);
    return;
  }
  if (isDebugPrint(expr)) {
    lines.push(`${indent(level)}(push ${extractNumericLiteral(expr.arguments[0], ctx)} gr-trace)`);
    return;
  }

  if (ts.isBinaryExpression(expr) && isAssignmentOperator(expr.operatorToken.kind)) {
    emitAssignment(expr.left, expr.right, expr.operatorToken.kind, lines, level, ctx);
    return;
  }

  if (ts.isPostfixUnaryExpression(expr) || ts.isPrefixUnaryExpression(expr)) {
    emitUnaryMutation(expr, lines, level, ctx);
    return;
  }

  if (ts.isCallExpression(expr) || ts.isAwaitExpression(expr)) {
    lines.push(`${indent(level)}${emitCall(expr, ctx)}`);
    return;
  }

  throw unsupported(expr, ctx, "expression statement");
}

function isAssignmentOperator(kind) {
  return kind === ts.SyntaxKind.FirstAssignment || kind === ts.SyntaxKind.PlusEqualsToken || kind === ts.SyntaxKind.MinusEqualsToken;
}

function emitAssignment(left, right, operator, lines, level, ctx) {
  const target = emitTarget(left, ctx);
  let value = emitValue(right, ctx);
  if (operator === ts.SyntaxKind.PlusEqualsToken) {
    value = emitAdd(target.read, value, right, ctx);
  } else if (operator === ts.SyntaxKind.MinusEqualsToken) {
    value = `(- (gr-num ${target.read}) (gr-num ${value}))`;
  }
  lines.push(`${indent(level)}${target.write(value)}`);
}

function emitPush(expr, lines, level, ctx) {
  const target = emitTarget(expr.expression.expression, ctx);
  const value = emitValue(expr.arguments[0], ctx);
  lines.push(`${indent(level)}${target.write(`(append ${target.read} (list ${value}))`)}`);
}

function emitForEach(expr, lines, level, ctx) {
  const callback = expr.arguments[0];
  if (!(ts.isFunctionExpression(callback) || ts.isArrowFunction(callback))) {
    throw unsupported(expr, ctx, "forEach callback");
  }
  if (callback.parameters.length !== 1 || !ts.isIdentifier(callback.parameters[0].name)) {
    throw unsupported(expr, ctx, "forEach parameters");
  }
  const loopVar = callback.parameters[0].name.text;
  const seqExpr = emitValue(expr.expression.expression, ctx);
  lines.push(`${indent(level)}(let ((gr_seq ${seqExpr}) (gr_i 0) (${loopVar} nil))`);
  lines.push(`${indent(level + 1)}(while (< gr_i (length gr_seq))`);
  lines.push(`${indent(level + 2)}(setq ${loopVar} (gr-index-ref gr_seq gr_i))`);
  const loopCtx = { ...ctx, locals: [...ctx.locals, loopVar] };
  if (ts.isBlock(callback.body)) {
    for (const stmt of callback.body.statements) {
      emitStatement(stmt, lines, level + 2, loopCtx);
    }
  } else {
    emitExpressionStatement(callback.body, lines, level + 2, loopCtx);
  }
  lines.push(`${indent(level + 2)}(setq gr_i (1+ gr_i))`);
  lines.push(`${indent(level + 1)})`);
  lines.push(`${indent(level)})`);
}

function emitUnaryMutation(expr, lines, level, ctx) {
  const node = ts.isPostfixUnaryExpression(expr) ? expr.operand : expr.operand;
  const target = emitTarget(node, ctx);
  const delta = expr.operator === ts.SyntaxKind.PlusPlusToken ? 1 : -1;
  lines.push(`${indent(level)}${target.write(`(+ (gr-num ${target.read}) ${delta})`)}`);
}

function emitIf(stmt, lines, level, ctx) {
  const cond = emitCondition(stmt.expression, ctx);
  const thenLines = emitBranch(stmt.thenStatement, level + 1, ctx);
  const elseLines = stmt.elseStatement ? emitBranch(stmt.elseStatement, level + 1, ctx) : [];
  lines.push(`${indent(level)}(if ${cond}`);
  lines.push(...wrapBranch(thenLines, level + 1));
  if (stmt.elseStatement) lines.push(...wrapBranch(elseLines, level + 1));
  lines.push(`${indent(level)})`);
}

function emitWhile(stmt, lines, level, ctx) {
  const cond = emitLoopCondition(stmt.expression, ctx);
  const bodyLines = emitLoopBranch(stmt.statement, level + 2, ctx);
  lines.push(`${indent(level)}(catch 'gr-break`);
  lines.push(`${indent(level + 1)}(while ${cond}`);
  lines.push(`${indent(level + 2)}(gr-step-tick)`);
  lines.push(`${indent(level + 2)}(catch 'gr-continue`);
  lines.push(...bodyLines);
  lines.push(`${indent(level + 2)})`);
  lines.push(`${indent(level + 1)})`);
  lines.push(`${indent(level)})`);
}

function emitFor(stmt, lines, level, ctx) {
  const counter = extractForCounter(stmt, ctx);
  if (stmt.initializer && ts.isVariableDeclarationList(stmt.initializer)) {
    for (const decl of stmt.initializer.declarations) {
      if (!ts.isIdentifier(decl.name)) throw unsupported(stmt, ctx, "for initializer");
      const init = decl.initializer ? emitValue(decl.initializer, ctx) : "nil";
      lines.push(`${indent(level)}(setq ${decl.name.text} ${init})`);
    }
  } else if (stmt.initializer) {
    throw unsupported(stmt, ctx, "for initializer");
  }
  const cond = stmt.condition ? emitLoopCondition(stmt.condition, ctx) : "t";
  const bodyLines = emitLoopBranch(stmt.statement, level + 2, ctx);
  const increment = emitForIncrement(stmt.incrementor, counter, ctx);
  lines.push(`${indent(level)}(catch 'gr-break`);
  lines.push(`${indent(level + 1)}(while ${cond}`);
  lines.push(`${indent(level + 2)}(gr-step-tick)`);
  lines.push(`${indent(level + 2)}(catch 'gr-continue`);
  lines.push(...bodyLines);
  lines.push(`${indent(level + 2)})`);
  lines.push(`${indent(level + 2)}${increment}`);
  lines.push(`${indent(level + 1)})`);
  lines.push(`${indent(level)})`);
}

function extractForCounter(stmt, ctx) {
  if (stmt.initializer && ts.isVariableDeclarationList(stmt.initializer) && stmt.initializer.declarations.length === 1) {
    const decl = stmt.initializer.declarations[0];
    if (ts.isIdentifier(decl.name)) return decl.name.text;
  }
  if (stmt.incrementor && (ts.isPostfixUnaryExpression(stmt.incrementor) || ts.isPrefixUnaryExpression(stmt.incrementor))) {
    const operand = stmt.incrementor.operand;
    if (ts.isIdentifier(operand)) return operand.text;
  }
  if (stmt.incrementor && ts.isBinaryExpression(stmt.incrementor) && ts.isIdentifier(stmt.incrementor.left)) {
    return stmt.incrementor.left.text;
  }
  throw unsupported(stmt, ctx, "for counter");
}

function emitForIncrement(node, counter, ctx) {
  if (!node) return "(progn nil)";
  if ((ts.isPostfixUnaryExpression(node) || ts.isPrefixUnaryExpression(node))
      && ts.isIdentifier(node.operand)
      && node.operand.text === counter
      && node.operator === ts.SyntaxKind.PlusPlusToken) {
    return `(setq ${counter} (+ (gr-num ${counter}) 1))`;
  }
  if (ts.isBinaryExpression(node) && ts.isIdentifier(node.left) && node.left.text === counter) {
    if (node.operatorToken.kind === ts.SyntaxKind.PlusEqualsToken) {
      return `(setq ${counter} (+ (gr-num ${counter}) (gr-num ${emitValue(node.right, ctx)})))`;
    }
    if (node.operatorToken.kind === ts.SyntaxKind.MinusEqualsToken) {
      return `(setq ${counter} (- (gr-num ${counter}) (gr-num ${emitValue(node.right, ctx)})))`;
    }
  }
  throw unsupported(node, ctx, "for increment");
}

function emitBranch(node, level, ctx) {
  const branchLines = [];
  if (ts.isBlock(node)) {
    for (const stmt of node.statements) emitStatement(stmt, branchLines, level, ctx);
    return branchLines;
  }
  emitStatement(node, branchLines, level, ctx);
  return branchLines;
}

function emitLoopBranch(node, level, ctx) {
  return emitBranch(node, level, ctx);
}

function wrapBranch(lines, level) {
  if (lines.length === 0) return [`${indent(level)}nil`];
  if (lines.length === 1) return [lines[0]];
  return [
    `${indent(level)}(progn`,
    ...lines,
    `${indent(level)})`,
  ];
}

function emitCall(expr, ctx) {
  if (ts.isAwaitExpression(expr)) {
    if (ts.isCallExpression(expr.expression) && isAwaitNoop(expr.expression)) {
      return "(progn nil)";
    }
    return emitCall(expr.expression, ctx);
  }
  if (!ts.isCallExpression(expr)) throw unsupported(expr, ctx, "non-call");

  if (ts.isIdentifier(expr.expression) && ctx.helperNames && ctx.helperNames.has(expr.expression.text)) {
    const args = expr.arguments.map((arg) => emitValue(arg, ctx));
    return `(${ctx.helperNames.get(expr.expression.text)}${args.length ? ` ${args.join(" ")}` : ""})`;
  }
  if (ts.isIdentifier(expr.expression) && expr.expression.text === "tf") {
    return emitValue(expr, ctx);
  }
  if (ts.isPropertyAccessExpression(expr.expression)
      && ts.isIdentifier(expr.expression.expression)
      && expr.expression.expression.text === "Adap"
      && expr.expression.name.text === "exist") {
    return `(gr-file-exists ${emitValue(expr.arguments[0], ctx)})`;
  }
  if (ts.isIdentifier(expr.expression) && isRuntimeName(expr.expression.text)) {
    const args = expr.arguments.map((arg) => emitValue(arg, ctx));
    return `(gr-run-func ${JSON.stringify(expr.expression.text)}${args.length ? ` ${args.join(" ")}` : ""})`;
  }
  if (ts.isIdentifier(expr.expression) && expr.expression.text === "cursorBeep") {
    return `(progn (gr-emit "dtw-play-sound" 100) (gr-run-func "func337"))`;
  }
  if (ts.isIdentifier(expr.expression) && expr.expression.text === "console") {
    return "(progn nil)";
  }

  const info = classifyCall(expr, ctx);
  const args = expr.arguments.map((arg) => emitValue(arg, ctx));

  if (info.kind === "core-call") {
    return `(gr-run-func ${JSON.stringify(info.name)}${args.length ? ` ${args.join(" ")}` : ""})`;
  }
  if (info.kind === "event") {
    // Adap.buffer(id, w, h, mode) both creates the buffer AND selects it
    // as the draw target (its adapter impl ends with gsel(id)).  The
    // generic event mapping emits only dtw-create-buffer and drops that
    // select, so boot-time procedural fills (e.g. func004's blue
    // message-box fill into buffer 12) land on the previously selected
    // buffer.  Mirror the select; bind the id to avoid double-evaluation.
    if (info.name === "dtw-create-buffer" && args.length >= 1) {
      const rest = args.slice(1);
      return `(let ((__cbuf ${args[0]})) (gr-emit "dtw-create-buffer" __cbuf${rest.length ? ` ${rest.join(" ")}` : ""}) (gr-emit "gui-select-buffer" __cbuf))`;
    }
    return `(gr-emit ${JSON.stringify(info.name)}${args.length ? ` ${args.join(" ")}` : ""})`;
  }
  if (info.kind === "special-reset-key") {
    return `(gr-reset-key ${args[0] || "0"})`;
  }
  if (info.kind === "special-gmode") {
    return `(gr-emit "gui-set-alpha" ${info.alpha(args)})`;
  }
  if (info.kind === "special-pos") {
    return `(progn (gr-set "__pos_x" ${args[0] || "0"}) (gr-set "__pos_y" ${args[1] || "0"}) (gr-emit "gui-set-position" ${args[0] || "0"} ${args[1] || "0"}))`;
  }
  if (info.kind === "special-font") {
    return `(gr-set "line_size" ${info.lineSize(args)})`;
  }
  if (info.kind === "special-bsave") {
    return `(gr-bsave ${args[0] || "\"\""} ${args[1] || "nil"} ${args[2] || "nil"} ${args[3] || "nil"})`;
  }
  if (info.kind === "special-mes") {
    return info.render(args);
  }
  if (info.kind === "special-gcopy") {
    return `(gr-emit "gui-draw-image-scaled" ${info.render(args)})`;
  }
  if (info.kind === "special-gzoom") {
    return `(gr-emit "gui-draw-image-scaled" ${info.render(args)})`;
  }
  if (info.kind === "noop") {
    return "(progn nil)";
  }
  throw unsupported(expr, ctx, "unsupported call target");
}

function isAwaitNoop(call) {
  return ts.isPropertyAccessExpression(call.expression)
    && ts.isIdentifier(call.expression.expression)
    && call.expression.expression.text === "Adap"
    && call.expression.name.text === "await_";
}

function classifyCall(call, ctx) {
  if (ts.isIdentifier(call.expression) && call.expression.text === "cursorBeep") {
    return { kind: "noop" };
  }
  if (ts.isIdentifier(call.expression) && (call.expression.text === "applyItem" || call.expression.text === "postProcessItem")) {
    return { kind: "noop" };
  }
  if (ts.isIdentifier(call.expression) && isRuntimeName(call.expression.text)) {
    return { kind: "core-call", name: call.expression.text };
  }
  if (!ts.isPropertyAccessExpression(call.expression)) throw unsupported(call, ctx, "call target");
  const root = call.expression.expression;
  const method = call.expression.name.text;
  if (ts.isIdentifier(root) && (root.text === "Func" || root.text === "Stand" || root.text === "Enemy" || root.text === "Title")) {
    if (/^func[\dA-Za-z]+$/i.test(method) || /^setMessage$/.test(method) || /^AutoDraw$/.test(method) || /^funcLangDisplay$/.test(method)) {
      if (method === "AutoDraw") return { kind: "core-call", name: "AutoDraw" };
      if (method === "setMessage") return { kind: "core-call", name: "setMessage" };
      return { kind: "core-call", name: method };
    }
    if (root.text === "Func" && method === "makepal") {
      return { kind: "event", name: "func-make-palette" };
    }
    if (root.text === "Func" && method === "imeset") {
      return { kind: "event", name: "func-ime-set" };
    }
    throw unsupported(call, ctx, `${root.text}.${method}`);
  }
  if (ts.isIdentifier(root) && root.text === "Music") {
    return { kind: "event", name: `music-${method}` };
  }
  if (ts.isIdentifier(root) && root.text === "Adap") {
    const eventMap = {
      DSPLAY: "dtw-play-sound",
      buffer: "dtw-create-buffer",
      screen_: "dtw-screen",
      picload: "dtw-load-image",
      gsel: "gui-select-buffer",
      redraw: "gui-present",
      color: "gui-set-color",
      color1: "gui-set-color",
      boxf: "gui-fill-rect",
      line: "gui-draw-line",
      pset: "gui-draw-point",
      bgscr: "dtw-screen",
      chgdisp: "dtw-change-display",
      cls: "dtw-clear-screen",
      grotate: "dtw-draw-image-rotated",
      objsel: "dtw-object-select",
      dialog: "dtw-dialog",
      chdir: "dtw-change-directory",
      delete_: "dtw-delete-file",
      clrobj: "dtw-clear-objects",
      title: "dtw-set-title",
      width: "dtw-resize-window",
      ShowWindow: "dtw-show-window",
      objmode: "dtw-object-mode",
      objsize: "dtw-object-size",
      combox: "dtw-combo-box",
      listbox: "dtw-list-box",
      button: "dtw-button",
      chkbox: "dtw-check-box",
      notesel: "dtw-note-select",
      noteload: "dtw-note-load",
      netclose: "dtw-network-close",
    };
    if (eventMap[method]) return { kind: "event", name: eventMap[method] };
    if (method === "ResetKey") return { kind: "special-reset-key" };
    if (method === "DMSTOP") return { kind: "event", name: "dtw-music-stop" };
    if (method === "wait" || method === "await_" || method === "onexit" || method === "onkey" || method === "ck_joystick" || method === "randomize" || method === "end" || method === "HMMINIT" || method === "oncmd_gosub" || method === "GetWindowLongA" || method === "SetWindowLongA" || method === "SetWindowPos" || method === "DSGETMASTERVOLUME") return { kind: "noop" };
    if (method === "bsave") return { kind: "special-bsave" };
    if (method === "gmode") {
      return {
        kind: "special-gmode",
        alpha(args) {
          if (args.length >= 4) return `(if (or (equal ${args[0]} 3) (equal ${args[0]} 4)) (gr-num ${args[3]}) 255)`;
          return "255";
        },
      };
    }
    if (method === "pos") return { kind: "special-pos" };
    if (method === "font") {
      return {
        kind: "special-font",
        lineSize(args) {
          return args[1] || "16";
        },
      };
    }
    if (method === "mes") {
      return {
        kind: "special-mes",
        render(args) {
          const lineSize = '(or (gr-get "line_size") 16)';
          return `(progn (gr-emit "gui-set-position" (or (gr-get "__pos_x") 0) (+ (gr-num (or (gr-get "__pos_y") 0)) (* (gr-num ${lineSize}) 0.9))) (gr-emit "gui-draw-text" ${args[0] || "\"\""}) (gr-set "__pos_y" (+ (gr-num (or (gr-get "__pos_y") 0)) (gr-num ${lineSize}))))`;
        },
      };
    }
    if (method === "gcopy") {
      return {
        kind: "special-gcopy",
        render(args) {
          const destX = '(or (gr-get "__pos_x") 0)';
          const destY = '(or (gr-get "__pos_y") 0)';
          const destW = args[5] || args[3] || "0";
          const destH = args[6] || args[4] || "0";
          return `${args[0] || "0"} ${args[1] || "0"} ${args[2] || "0"} ${args[3] || "0"} ${args[4] || "0"} ${destX} ${destY} ${destW} ${destH}`;
        },
      };
    }
    if (method === "gzoom") {
      return {
        kind: "special-gzoom",
        render(args) {
          const destX = '(or (gr-get "__pos_x") 0)';
          const destY = '(or (gr-get "__pos_y") 0)';
          return `${args[2] || "0"} ${args[3] || "0"} ${args[4] || "0"} ${args[5] || "0"} ${args[6] || "0"} ${destX} ${destY} ${args[0] || "0"} ${args[1] || "0"}`;
        },
      };
    }
    throw unsupported(call, ctx, `Adap.${method}`);
  }
  if (ts.isIdentifier(root) && root.text === "window" && method === "addEventListener") {
    return { kind: "noop" };
  }
  if (ts.isIdentifier(root) && root.text === "console") {
    return { kind: "noop" };
  }
  throw unsupported(call, ctx, "call root");
}

function emitTarget(node, ctx) {
  if (ts.isIdentifier(node) && ctx.locals.includes(node.text)) {
    return {
      read: node.text,
      write(value) { return `(setq ${node.text} ${value})`; },
    };
  }
  if (ts.isPropertyAccessExpression(node)) {
    if (isGvarPropertyAccess(node)) {
      const slot = extractGvarSlot(node, ctx);
      return {
        read: `(gr-get ${emitSlotKey(slot)})`,
        write(value) { return `(gr-set ${emitSlotKey(slot)} ${value})`; },
      };
    }
    const base = emitValue(node.expression, ctx);
    const prop = JSON.stringify(node.name.text);
    return {
      read: `(gr-prop-ref ${base} ${prop})`,
      write(value) { return `(gr-prop-set ${base} ${prop} ${value})`; },
    };
  }
  if (ts.isElementAccessExpression(node)) {
    const arr = emitValue(node.expression, ctx);
    const index = emitValue(node.argumentExpression, ctx);
    return {
      read: `(gr-index-ref ${arr} ${index})`,
      write(value) {
        return `(let ((arr ${arr}) (idx ${index}) (val ${value})) (when (and (arrayp arr) (integerp idx) (>= idx 0) (< idx (length arr))) (aset arr idx val)))`;
      },
    };
  }
  throw unsupported(node, ctx, "target");
}

function emitCondition(node, ctx) {
  if (ts.isParenthesizedExpression(node)) return emitCondition(node.expression, ctx);
  if (ts.isPrefixUnaryExpression(node) && node.operator === ts.SyntaxKind.ExclamationToken) {
    return `(not ${emitCondition(node.operand, ctx)})`;
  }
  if (ts.isCallExpression(node) && ts.isIdentifier(node.expression) && node.expression.text === "noAbilityActive") {
    return "(and (equal (gr-get 1240) 0) (equal (gr-get 1999) 0) (equal (gr-get 2000) 0) (equal (gr-get 2001) 0) (equal (gr-get 1950) 0) (equal (gr-get 2002) 0) (equal (gr-get 2003) 0) (equal (gr-get 2004) 0) (equal (gr-get 2005) 0) (equal (gr-get 2006) 0) (equal (gr-get 2007) 0))";
  }
  if (ts.isBinaryExpression(node)) {
    const op = node.operatorToken.kind;
    if (op === ts.SyntaxKind.AmpersandAmpersandToken) {
      return `(and ${emitCondition(node.left, ctx)} ${emitCondition(node.right, ctx)})`;
    }
    if (op === ts.SyntaxKind.BarBarToken) {
      return `(or ${emitCondition(node.left, ctx)} ${emitCondition(node.right, ctx)})`;
    }
    const lhs = emitValue(node.left, ctx);
    const rhs = emitValue(node.right, ctx);
    switch (op) {
      case ts.SyntaxKind.EqualsEqualsToken:
      case ts.SyntaxKind.EqualsEqualsEqualsToken:
        return `(equal ${lhs} ${rhs})`;
      case ts.SyntaxKind.ExclamationEqualsToken:
      case ts.SyntaxKind.ExclamationEqualsEqualsToken:
        return `(not (equal ${lhs} ${rhs}))`;
      case ts.SyntaxKind.GreaterThanToken:
        return `(> ${emitNumericValue(node.left, ctx)} ${emitNumericValue(node.right, ctx)})`;
      case ts.SyntaxKind.GreaterThanEqualsToken:
        return `(>= ${emitNumericValue(node.left, ctx)} ${emitNumericValue(node.right, ctx)})`;
      case ts.SyntaxKind.LessThanToken:
        return `(< ${emitNumericValue(node.left, ctx)} ${emitNumericValue(node.right, ctx)})`;
      case ts.SyntaxKind.LessThanEqualsToken:
        return `(<= ${emitNumericValue(node.left, ctx)} ${emitNumericValue(node.right, ctx)})`;
      default:
        throw unsupported(node, ctx, "if condition");
    }
  }
  return emitTruth(node, ctx);
}

function emitLoopCondition(node, ctx) {
  if (node.kind === ts.SyntaxKind.TrueKeyword) return "t";
  return emitCondition(node, ctx);
}

function emitNumericValue(node, ctx) {
  return `(gr-num ${emitValue(node, ctx)})`;
}

function emitTruth(node, ctx) {
  const value = emitValue(node, ctx);
  return `(not (or (equal ${value} nil) (equal ${value} 0)))`;
}

function emitValue(node, ctx) {
  if (!node) return "nil";
  if (ts.isParenthesizedExpression(node)) return emitValue(node.expression, ctx);
  if (ts.isNumericLiteral(node)) return String(Number(node.text));
  if (ts.isStringLiteral(node)) return JSON.stringify(node.text);
  if (node.kind === ts.SyntaxKind.TrueKeyword) return "t";
  if (node.kind === ts.SyntaxKind.FalseKeyword) return "nil";
  if (node.kind === ts.SyntaxKind.NullKeyword) return "nil";
  if (ts.isIdentifier(node)) {
    if (node.text === "document") return "nil";
    if (node.text === "undefined") return "nil";
    if (ctx.locals.includes(node.text)) return node.text;
    if (ctx.fileConsts && ctx.fileConsts.has(node.text)) return emitValue(ctx.fileConsts.get(node.text), ctx);
    throw unsupported(node, ctx, `identifier ${node.text}`);
  }
  if (ts.isTypeOfExpression(node)) {
    if (ts.isIdentifier(node.expression) && node.expression.text === "document") {
      return "\"undefined\"";
    }
    return "\"object\"";
  }
  if (isPropertyAccessLike(node)) {
    if (isGvarPropertyAccess(node)) {
      return `(gr-get ${emitSlotKey(extractGvarSlot(node, ctx))})`;
    }
    if (ts.isIdentifier(node.expression)
        && ["Func", "Title", "Stand", "Enemy"].includes(node.expression.text)
        && /^func[\dA-Za-z]+$/i.test(node.name.text)) {
      return JSON.stringify(node.name.text);
    }
    return `(gr-prop-ref ${emitValue(node.expression, ctx)} ${JSON.stringify(node.name.text)})`;
  }
  if (isElementAccessLike(node)) {
    return `(gr-index-ref ${emitValue(node.expression, ctx)} ${emitValue(node.argumentExpression, ctx)})`;
  }
  if (ts.isPrefixUnaryExpression(node) && node.operator === ts.SyntaxKind.MinusToken) {
    return `(- ${emitNumericValue(node.operand, ctx)})`;
  }
  if (ts.isBinaryExpression(node)) {
    if (node.operatorToken.kind === ts.SyntaxKind.QuestionQuestionToken) {
      return `(let ((gr_lhs ${emitValue(node.left, ctx)})) (if (equal gr_lhs nil) ${emitValue(node.right, ctx)} gr_lhs))`;
    }
    if (node.operatorToken.kind === ts.SyntaxKind.BarBarToken) {
      return `(let ((gr_lhs ${emitValue(node.left, ctx)})) (if (not (or (equal gr_lhs nil) (equal gr_lhs 0))) gr_lhs ${emitValue(node.right, ctx)}))`;
    }
    if (node.operatorToken.kind === ts.SyntaxKind.AmpersandAmpersandToken) {
      return `(let ((gr_lhs ${emitValue(node.left, ctx)})) (if (not (or (equal gr_lhs nil) (equal gr_lhs 0))) ${emitValue(node.right, ctx)} gr_lhs))`;
    }
    if (isAssignmentOperator(node.operatorToken.kind)) {
      const target = emitTarget(node.left, ctx);
      const value = emitValue(node.right, ctx);
      return `(let ((gr_tmp ${value})) ${target.write("gr_tmp")} gr_tmp)`;
    }
    if (node.operatorToken.kind === ts.SyntaxKind.PlusToken && isStringConcatExpression(node)) {
      return `(concat (format "%s" ${emitValue(node.left, ctx)}) (format "%s" ${emitValue(node.right, ctx)}))`;
    }
    const lhs = emitNumericValue(node.left, ctx);
    const rhs = emitNumericValue(node.right, ctx);
    switch (node.operatorToken.kind) {
      case ts.SyntaxKind.PlusToken:
        return `(+ ${lhs} ${rhs})`;
      case ts.SyntaxKind.MinusToken:
        return `(- ${lhs} ${rhs})`;
      case ts.SyntaxKind.AsteriskToken:
        return `(* ${lhs} ${rhs})`;
      case ts.SyntaxKind.SlashToken:
        return `(/ ${lhs} ${rhs})`;
      case ts.SyntaxKind.PercentToken:
        return `(% ${lhs} ${rhs})`;
      case ts.SyntaxKind.EqualsEqualsToken:
      case ts.SyntaxKind.EqualsEqualsEqualsToken:
        return `(equal ${emitValue(node.left, ctx)} ${emitValue(node.right, ctx)})`;
      case ts.SyntaxKind.ExclamationEqualsToken:
      case ts.SyntaxKind.ExclamationEqualsEqualsToken:
        return `(not (equal ${emitValue(node.left, ctx)} ${emitValue(node.right, ctx)}))`;
      default:
        throw unsupported(node, ctx, "value binary expression");
    }
  }
  if (ts.isConditionalExpression(node)) {
    return `(if ${emitCondition(node.condition, ctx)} ${emitValue(node.whenTrue, ctx)} ${emitValue(node.whenFalse, ctx)})`;
  }
  if (ts.isAwaitExpression(node)) {
    if (ts.isCallExpression(node.expression) && isAwaitNoop(node.expression)) return "nil";
    return emitValue(node.expression, ctx);
  }
  if (ts.isCallExpression(node)) {
    if (ts.isIdentifier(node.expression) && ctx.helperNames && ctx.helperNames.has(node.expression.text)) {
      const args = node.arguments.map((arg) => emitValue(arg, ctx));
      return `(${ctx.helperNames.get(node.expression.text)}${args.length ? ` ${args.join(" ")}` : ""})`;
    }
    if (ts.isIdentifier(node.expression) && node.expression.text === "t") {
      return `(gr-i18n-t ${emitValue(node.arguments[0], ctx)})`;
    }
    if (ts.isIdentifier(node.expression) && node.expression.text === "tf") {
      const args = node.arguments.map((arg) => emitValue(arg, ctx));
      return `(gr-format ${args.join(" ")})`;
    }
    if (ts.isIdentifier(node.expression) && node.expression.text === "Array" && node.arguments.length === 0) {
      return "nil";
    }
    if (ts.isIdentifier(node.expression) && (node.expression.text === "applyItem" || node.expression.text === "postProcessItem")) {
      return "nil";
    }
    if (isFindCall(node, ctx)) {
      return emitFindCall(node, ctx);
    }
    if (!isPropertyAccessLike(node.expression)) throw unsupported(node, ctx, "value call");
    const root = node.expression.expression;
    const method = node.expression.name.text;
    if (ts.isIdentifier(root) && root.text === "Math") {
      if (method === "floor") return `(floor ${emitNumericValue(node.arguments[0], ctx)})`;
      throw unsupported(node, ctx, `Math.${method}`);
    }
    if (ts.isPropertyAccessExpression(root)
        && ts.isIdentifier(root.expression)
        && root.expression.text === "Class") {
      const className = root.name.text;
      if (className === "ItemInfo" && method === "dim") {
        return `(gr-item-info-dim ${emitNumericValue(node.arguments[0], ctx)})`;
      }
      if (className === "ItemInfo" && method === "Load") {
        return `(gr-item-info-load ${emitValue(node.arguments[0], ctx)})`;
      }
      if (className === "CharactorInfo" && method === "dim") {
        return `(gr-charactor-info-dim ${emitNumericValue(node.arguments[0], ctx)})`;
      }
      if (className === "CharactorInfo" && method === "Load") {
        return `(gr-charactor-info-load ${emitValue(node.arguments[0], ctx)})`;
      }
    }
    if (method === "toString" && node.arguments.length === 0) {
      return `(format "%s" ${emitValue(root, ctx)})`;
    }
    if (method === "contains" && node.arguments.length === 1) {
      return "nil";
    }
    if (method === "Save" && node.arguments.length === 0) {
      return `(gr-record-save ${emitValue(root, ctx)})`;
    }
    if (ts.isIdentifier(root) && root.text === "Adap") {
      if (method === "rnd") return `(gr-random ${emitNumericValue(node.arguments[0], ctx)})`;
      if (method === "int") return `(truncate (gr-num ${emitValue(node.arguments[0], ctx)}))`;
      if (method === "getkey") return `(gr-read-key-state ${emitValue(node.arguments[0], ctx)})`;
      if (method === "exist") return `(gr-file-exists ${emitValue(node.arguments[0], ctx)})`;
      if (method === "bload") {
        const args = node.arguments.map((arg) => emitValue(arg, ctx));
        return `(gr-bload ${args[0] || "\"\""} ${args[1] || "nil"} ${args[2] || "nil"} ${args[3] || "nil"})`;
      }
      if (method === "peek") return `(gr-peek-char ${emitValue(node.arguments[0], ctx)} ${emitValue(node.arguments[1], ctx)})`;
      if (method === "dirinfo") return "\"\"";
      if (method === "stick" || method === "ginfo" || method === "ck_joystick") return "0";
      if (method === "dim") return `(gr-make-array ${node.arguments.map((arg) => emitValue(arg, ctx)).join(" ")})`;
      if (method === "sdim") return `(gr-make-string-array ${node.arguments.map((arg) => emitValue(arg, ctx)).join(" ")})`;
    }
    throw unsupported(node, ctx, `value call ${method}`);
  }
  if (ts.isArrayLiteralExpression(node)) {
    if (node.elements.length === 0) return "nil";
    return `(vector ${node.elements.map((element) => emitValue(element, ctx)).join(" ")})`;
  }
  if (ts.isObjectLiteralExpression(node)) {
    const entries = node.properties.map((prop) => {
      if (!ts.isPropertyAssignment(prop)) throw unsupported(prop, ctx, "object literal property");
      const key = emitObjectKey(prop.name, ctx);
      const value = emitValue(prop.initializer, ctx);
      return `(puthash ${key} ${value} tbl)`;
    });
    return `(let ((tbl (make-hash-table :test 'equal))) ${entries.join(" ")} tbl)`;
  }
  if (ts.isFunctionExpression(node) || ts.isArrowFunction(node)) {
    return "nil";
  }
  throw unsupported(node, ctx, "value");
}

function isPropertyAccessLike(node) {
  return ts.isPropertyAccessExpression(node)
    || (typeof ts.isPropertyAccessChain === "function" && ts.isPropertyAccessChain(node));
}

function isElementAccessLike(node) {
  return ts.isElementAccessExpression(node)
    || (typeof ts.isElementAccessChain === "function" && ts.isElementAccessChain(node));
}

function emitObjectKey(nameNode, ctx) {
  if (ts.isIdentifier(nameNode)) return JSON.stringify(nameNode.text);
  if (ts.isStringLiteral(nameNode)) return JSON.stringify(nameNode.text);
  if (ts.isNumericLiteral(nameNode)) return String(Number(nameNode.text));
  throw unsupported(nameNode, ctx, "object key");
}

function isFindCall(node, _ctx) {
  return ts.isCallExpression(node)
    && isPropertyAccessLike(node.expression)
    && node.expression.name.text === "find"
    && node.arguments.length === 1
    && (ts.isArrowFunction(node.arguments[0]) || ts.isFunctionExpression(node.arguments[0]));
}

function emitFindCall(node, ctx) {
  const callback = node.arguments[0];
  if (callback.parameters.length !== 1 || !ts.isIdentifier(callback.parameters[0].name)) {
    throw unsupported(node, ctx, "find callback parameters");
  }
  const loopVar = callback.parameters[0].name.text;
  const seqExpr = emitValue(node.expression.expression, ctx);
  const loopCtx = { ...ctx, locals: [...ctx.locals, loopVar] };
  let predicate;
  if (ts.isBlock(callback.body)) {
    const returnStmt = callback.body.statements.find((stmt) => ts.isReturnStatement(stmt));
    if (!returnStmt || !returnStmt.expression) {
      throw unsupported(node, ctx, "find callback return");
    }
    predicate = emitCondition(returnStmt.expression, loopCtx);
  } else {
    predicate = emitCondition(callback.body, loopCtx);
  }
  return `(let ((gr_seq ${seqExpr}) (gr_i 0) (gr_found nil) (${loopVar} nil)) (while (and (< gr_i (length gr_seq)) (equal gr_found nil)) (setq ${loopVar} (gr-index-ref gr_seq gr_i)) (if ${predicate} (setq gr_found ${loopVar})) (setq gr_i (1+ gr_i))) gr_found)`;
}

function isStringConcatExpression(node) {
  if (ts.isStringLiteral(node)) return true;
  if (ts.isBinaryExpression(node) && node.operatorToken.kind === ts.SyntaxKind.PlusToken) {
    return isStringConcatExpression(node.left) || isStringConcatExpression(node.right);
  }
  return false;
}

function isGvarPropertyAccess(node) {
  return ts.isIdentifier(node.expression) && node.expression.text === "Gvar";
}

function extractGvarSlot(node, ctx) {
  if (!ts.isPropertyAccessExpression(node)) throw unsupported(node, ctx, "non-Gvar slot");
  if (!isGvarPropertyAccess(node)) throw unsupported(node, ctx, "non-Gvar access");
  const match = /^var_(\d+)$/.exec(node.name.text);
  if (match) return Number(match[1]);
  return node.name.text;
}

function emitSlotKey(slot) {
  return typeof slot === "number" ? String(slot) : JSON.stringify(slot);
}

function emitAdd(leftValue, rightValue, rightNode, ctx) {
  return isStringConcatExpression(rightNode)
    ? `(concat (format "%s" ${leftValue}) (format "%s" ${rightValue}))`
    : `(+ (gr-num ${leftValue}) (gr-num ${rightValue}))`;
}

function extractNumericLiteral(node, ctx) {
  if (!ts.isNumericLiteral(node)) throw unsupported(node, ctx, "non-numeric literal");
  return Number(node.text);
}

function isDebugPrint(expr) {
  return ts.isCallExpression(expr)
    && ts.isPropertyAccessExpression(expr.expression)
    && ts.isIdentifier(expr.expression.expression)
    && expr.expression.expression.text === "Adap"
    && expr.expression.name.text === "dbgprt"
    && expr.arguments.length === 1;
}

function indent(level) {
  return "  ".repeat(level);
}

function unsupported(node, ctx, detail) {
  const snippet = node.getText(ctx.sf).replace(/\s+/g, " ").trim();
  return new Error(`${ctx.name}: unsupported ${detail}: ${snippet}`);
}

function isForEachCall(expr) {
  return ts.isPropertyAccessExpression(expr.expression)
    && expr.expression.name.text === "forEach"
    && expr.arguments.length === 1
    && (ts.isFunctionExpression(expr.arguments[0]) || ts.isArrowFunction(expr.arguments[0]));
}

function isPushCall(expr) {
  return ts.isPropertyAccessExpression(expr.expression)
    && expr.expression.name.text === "push"
    && expr.arguments.length === 1;
}

module.exports = {
  transpileFunc,
};
