#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const ts = require("typescript");

const repoRoot = path.resolve(__dirname, "..");

if (require.main === module) {
  main();
}

function main() {
  const args = process.argv.slice(2);
  const srcRoot = path.resolve(
    valueAfter(args, "--src-root") || path.join(repoRoot, "src", "renderer")
  );
  const outPath = path.resolve(
    valueAfter(args, "--out") || path.join(repoRoot, "nelisp_runtime", "gamedata-conditional.el")
  );
  let names = valuesAfter(args, "--name");
  const namesFile = valueAfter(args, "--names-file");
  if (namesFile) {
    names = names.concat(
      fs.readFileSync(path.resolve(namesFile), "utf8").split(/\s+/).filter(Boolean)
    );
  }
  if (!fs.existsSync(srcRoot)) throw new Error(`--src-root missing or not found: ${srcRoot}`);
  if (names.length === 0) throw new Error("pass at least one --name funcNNN or --names-file");

  const fileIndex = buildDefinitionIndex(srcRoot);
  const translated = [];
  const skipped = [];
  const noSource = [];
  for (const name of dedupe(names).sort(byFuncNumber)) {
    const file = findSourceFile(fileIndex, name);
    if (!file) {
      noSource.push(name);
      continue;
    }
    try {
      translated.push({
        name,
        body: transpileFunc(name, file),
      });
    } catch (error) {
      skipped.push([name, error.message]);
    }
  }

  const output = [
    ";;; gamedata-conditional.el --- generated native conditional funcs for NeLisp -*- coding: utf-8; -*-",
    ";; Generated by tools/generate_nelisp_conditional_runtime.js from src/renderer/**/*.ts.",
    ";; Do not edit by hand.",
    "",
    ...translated.flatMap(({ name, body }) => [
      `(defun gr-native-${name} (&rest _args)`,
      body.map((line) => `  ${line}`).join("\n"),
      ")",
      "",
      `(gr-defnative "${name}" #'gr-native-${name})`,
      "",
    ]),
    "(provide 'gamedata-conditional)",
    "",
  ].join("\n");

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, output, "utf8");
  console.log(JSON.stringify({
    out: path.relative(repoRoot, outPath),
    translated: translated.map((entry) => entry.name),
    skipped,
    noSource,
  }, null, 2));
}

function valueAfter(args, flag) {
  const index = args.indexOf(flag);
  return index >= 0 ? args[index + 1] : null;
}

function valuesAfter(args, flag) {
  const out = [];
  for (let i = 0; i < args.length; i++) {
    if (args[i] === flag) out.push(args[i + 1]);
  }
  return out;
}

function dedupe(values) {
  return [...new Set(values)];
}

function byFuncNumber(a, b) {
  const na = Number(a.replace(/\D/g, ""));
  const nb = Number(b.replace(/\D/g, ""));
  return na - nb || a.localeCompare(b);
}

function buildDefinitionIndex(root) {
  const files = [];
  walk(root, files);
  const defs = new Map();
  for (const file of files.filter((entry) => entry.endsWith(".ts"))) {
    const source = fs.readFileSync(file, "utf8");
    const sf = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
    for (const stmt of sf.statements) {
      if (ts.isFunctionDeclaration(stmt) && stmt.name && /^func[\dA-Za-z]+$/i.test(stmt.name.text)) {
        if (!defs.has(stmt.name.text)) defs.set(stmt.name.text, file);
      }
    }
  }
  return defs;
}

function walk(dir, out) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else out.push(full);
  }
}

function findSourceFile(defs, name) {
  return defs.get(name) || null;
}

function transpileFunc(name, file) {
  const source = fs.readFileSync(file, "utf8");
  const sf = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const func = sf.statements.find((stmt) => ts.isFunctionDeclaration(stmt) && stmt.name && stmt.name.text === name);
  if (!func || !func.body) throw new Error(`function ${name} not found`);

  const bodyStatements = func.body.statements.filter((stmt) => !isGeneratedGuard(stmt));
  if (bodyStatements.length === 0) throw new Error(`${name}: empty function body`);

  const locals = collectLocals(func.body);
  const ctx = { name, sf, locals };
  const lines = [];
  lines.push(`"${name}: transpiled from TypeScript conditional fallback."`);
  lines.push("(catch 'gr-return");
  if (locals.length) {
    lines.push(`  (let (${locals.map((name) => `(${name} nil)`).join(" ")})`);
    for (const stmt of bodyStatements) {
      emitStatement(stmt, lines, 2, ctx);
    }
    lines.push("  )");
  } else {
    for (const stmt of bodyStatements) {
      emitStatement(stmt, lines, 1, ctx);
    }
  }
  lines.push(")");
  return lines;
}

function collectLocals(node) {
  const locals = new Set();
  function visit(current) {
    if (ts.isVariableDeclaration(current) && ts.isIdentifier(current.name)) {
      locals.add(current.name.text);
    }
    if (ts.isForStatement(current) && current.initializer && ts.isVariableDeclarationList(current.initializer)) {
      for (const decl of current.initializer.declarations) {
        if (ts.isIdentifier(decl.name)) locals.add(decl.name.text);
      }
    }
    ts.forEachChild(current, visit);
  }
  visit(node);
  return [...locals].sort();
}

function isGeneratedGuard(stmt) {
  if (!ts.isIfStatement(stmt)) return false;
  const cond = stmt.expression;
  if (!ts.isCallExpression(cond)) return false;
  if (!ts.isIdentifier(cond.expression) || cond.expression.text !== "shouldUseGeneratedGameFunction") return false;
  if (cond.arguments.length !== 1 || !ts.isStringLiteral(cond.arguments[0])) return false;
  if (!stmt.thenStatement || !ts.isBlock(stmt.thenStatement)) return false;
  const inner = stmt.thenStatement.statements;
  if (inner.length !== 2) return false;
  return ts.isExpressionStatement(inner[0]) && ts.isReturnStatement(inner[1]);
}

function emitStatement(stmt, lines, level, ctx) {
  if (ts.isExpressionStatement(stmt)) {
    emitExpressionStatement(stmt.expression, lines, level, ctx);
    return;
  }
  if (ts.isVariableStatement(stmt)) {
    emitVariableStatement(stmt, lines, level, ctx);
    return;
  }
  if (ts.isWhileStatement(stmt)) {
    emitWhile(stmt, lines, level, ctx);
    return;
  }
  if (ts.isForStatement(stmt)) {
    emitFor(stmt, lines, level, ctx);
    return;
  }
  if (ts.isIfStatement(stmt)) {
    emitIf(stmt, lines, level, ctx);
    return;
  }
  if (ts.isReturnStatement(stmt)) {
    if (stmt.expression) throw unsupported(stmt, ctx, "return with value");
    lines.push(`${indent(level)}(throw 'gr-return nil)`);
    return;
  }
  if (ts.isBreakStatement(stmt)) {
    lines.push(`${indent(level)}(throw 'gr-break nil)`);
    return;
  }
  if (ts.isContinueStatement(stmt)) {
    lines.push(`${indent(level)}(throw 'gr-continue nil)`);
    return;
  }
  throw unsupported(stmt, ctx, ts.SyntaxKind[stmt.kind]);
}

function emitVariableStatement(stmt, lines, level, ctx) {
  for (const decl of stmt.declarationList.declarations) {
    if (!ts.isIdentifier(decl.name)) throw unsupported(decl, ctx, "destructuring declaration");
    const init = decl.initializer ? emitValue(decl.initializer, ctx) : "nil";
    lines.push(`${indent(level)}(setq ${decl.name.text} ${init})`);
  }
}

function emitExpressionStatement(expr, lines, level, ctx) {
  if (isDebugPrint(expr)) {
    lines.push(`${indent(level)}(push ${extractNumericLiteral(expr.arguments[0], ctx)} gr-trace)`);
    return;
  }

  if (ts.isBinaryExpression(expr) && isAssignmentOperator(expr.operatorToken.kind)) {
    emitAssignment(expr.left, expr.right, expr.operatorToken.kind, lines, level, ctx);
    return;
  }

  if (ts.isPostfixUnaryExpression(expr) || ts.isPrefixUnaryExpression(expr)) {
    emitUnaryMutation(expr, lines, level, ctx);
    return;
  }

  if (ts.isCallExpression(expr) || ts.isAwaitExpression(expr)) {
    lines.push(`${indent(level)}${emitCall(expr, ctx)}`);
    return;
  }

  throw unsupported(expr, ctx, "expression statement");
}

function isAssignmentOperator(kind) {
  return kind === ts.SyntaxKind.FirstAssignment || kind === ts.SyntaxKind.PlusEqualsToken || kind === ts.SyntaxKind.MinusEqualsToken;
}

function emitAssignment(left, right, operator, lines, level, ctx) {
  const target = emitTarget(left, ctx);
  let value = emitValue(right, ctx);
  if (operator === ts.SyntaxKind.PlusEqualsToken) {
    value = emitAdd(target.read, value, right, ctx);
  } else if (operator === ts.SyntaxKind.MinusEqualsToken) {
    value = `(- (gr-num ${target.read}) (gr-num ${value}))`;
  }
  lines.push(`${indent(level)}${target.write(value)}`);
}

function emitUnaryMutation(expr, lines, level, ctx) {
  const node = ts.isPostfixUnaryExpression(expr) ? expr.operand : expr.operand;
  const target = emitTarget(node, ctx);
  const delta = expr.operator === ts.SyntaxKind.PlusPlusToken ? 1 : -1;
  lines.push(`${indent(level)}${target.write(`(+ (gr-num ${target.read}) ${delta})`)}`);
}

function emitIf(stmt, lines, level, ctx) {
  const cond = emitCondition(stmt.expression, ctx);
  const thenLines = emitBranch(stmt.thenStatement, level + 1, ctx);
  const elseLines = stmt.elseStatement ? emitBranch(stmt.elseStatement, level + 1, ctx) : [];
  lines.push(`${indent(level)}(if ${cond}`);
  lines.push(...wrapBranch(thenLines, level + 1));
  if (stmt.elseStatement) lines.push(...wrapBranch(elseLines, level + 1));
  lines.push(`${indent(level)})`);
}

function emitWhile(stmt, lines, level, ctx) {
  const cond = emitLoopCondition(stmt.expression, ctx);
  const bodyLines = emitLoopBranch(stmt.statement, level + 2, ctx);
  lines.push(`${indent(level)}(catch 'gr-break`);
  lines.push(`${indent(level + 1)}(while ${cond}`);
  lines.push(`${indent(level + 2)}(gr-step-tick)`);
  lines.push(`${indent(level + 2)}(catch 'gr-continue`);
  lines.push(...bodyLines);
  lines.push(`${indent(level + 2)})`);
  lines.push(`${indent(level + 1)})`);
  lines.push(`${indent(level)})`);
}

function emitFor(stmt, lines, level, ctx) {
  const counter = extractForCounter(stmt, ctx);
  if (stmt.initializer && ts.isVariableDeclarationList(stmt.initializer)) {
    for (const decl of stmt.initializer.declarations) {
      if (!ts.isIdentifier(decl.name)) throw unsupported(stmt, ctx, "for initializer");
      const init = decl.initializer ? emitValue(decl.initializer, ctx) : "nil";
      lines.push(`${indent(level)}(setq ${decl.name.text} ${init})`);
    }
  } else if (stmt.initializer) {
    throw unsupported(stmt, ctx, "for initializer");
  }
  const cond = stmt.condition ? emitLoopCondition(stmt.condition, ctx) : "t";
  const bodyLines = emitLoopBranch(stmt.statement, level + 2, ctx);
  const increment = emitForIncrement(stmt.incrementor, counter, ctx);
  lines.push(`${indent(level)}(catch 'gr-break`);
  lines.push(`${indent(level + 1)}(while ${cond}`);
  lines.push(`${indent(level + 2)}(gr-step-tick)`);
  lines.push(`${indent(level + 2)}(catch 'gr-continue`);
  lines.push(...bodyLines);
  lines.push(`${indent(level + 2)})`);
  lines.push(`${indent(level + 2)}${increment}`);
  lines.push(`${indent(level + 1)})`);
  lines.push(`${indent(level)})`);
}

function extractForCounter(stmt, ctx) {
  if (stmt.initializer && ts.isVariableDeclarationList(stmt.initializer) && stmt.initializer.declarations.length === 1) {
    const decl = stmt.initializer.declarations[0];
    if (ts.isIdentifier(decl.name)) return decl.name.text;
  }
  if (stmt.incrementor && (ts.isPostfixUnaryExpression(stmt.incrementor) || ts.isPrefixUnaryExpression(stmt.incrementor))) {
    const operand = stmt.incrementor.operand;
    if (ts.isIdentifier(operand)) return operand.text;
  }
  if (stmt.incrementor && ts.isBinaryExpression(stmt.incrementor) && ts.isIdentifier(stmt.incrementor.left)) {
    return stmt.incrementor.left.text;
  }
  throw unsupported(stmt, ctx, "for counter");
}

function emitForIncrement(node, counter, ctx) {
  if (!node) return "(progn nil)";
  if ((ts.isPostfixUnaryExpression(node) || ts.isPrefixUnaryExpression(node))
      && ts.isIdentifier(node.operand)
      && node.operand.text === counter
      && node.operator === ts.SyntaxKind.PlusPlusToken) {
    return `(setq ${counter} (+ (gr-num ${counter}) 1))`;
  }
  if (ts.isBinaryExpression(node) && ts.isIdentifier(node.left) && node.left.text === counter) {
    if (node.operatorToken.kind === ts.SyntaxKind.PlusEqualsToken) {
      return `(setq ${counter} (+ (gr-num ${counter}) (gr-num ${emitValue(node.right, ctx)})))`;
    }
    if (node.operatorToken.kind === ts.SyntaxKind.MinusEqualsToken) {
      return `(setq ${counter} (- (gr-num ${counter}) (gr-num ${emitValue(node.right, ctx)})))`;
    }
  }
  throw unsupported(node, ctx, "for increment");
}

function emitBranch(node, level, ctx) {
  const branchLines = [];
  if (ts.isBlock(node)) {
    for (const stmt of node.statements) emitStatement(stmt, branchLines, level, ctx);
    return branchLines;
  }
  emitStatement(node, branchLines, level, ctx);
  return branchLines;
}

function emitLoopBranch(node, level, ctx) {
  return emitBranch(node, level, ctx);
}

function wrapBranch(lines, level) {
  if (lines.length === 0) return [`${indent(level)}nil`];
  if (lines.length === 1) return [lines[0]];
  return [
    `${indent(level)}(progn`,
    ...lines,
    `${indent(level)})`,
  ];
}

function emitCall(expr, ctx) {
  if (ts.isAwaitExpression(expr)) {
    if (ts.isCallExpression(expr.expression) && isAwaitNoop(expr.expression)) {
      return "(progn nil)";
    }
    return emitCall(expr.expression, ctx);
  }
  if (!ts.isCallExpression(expr)) throw unsupported(expr, ctx, "non-call");

  if (ts.isIdentifier(expr.expression) && expr.expression.text === "cursorBeep") {
    return `(progn (gr-emit "dtw-play-sound" 100) (gr-run-func "func337"))`;
  }
  if (ts.isIdentifier(expr.expression) && expr.expression.text === "console") {
    return "(progn nil)";
  }

  const info = classifyCall(expr, ctx);
  const args = expr.arguments.map((arg) => emitValue(arg, ctx));

  if (info.kind === "core-call") {
    return `(gr-run-func ${JSON.stringify(info.name)}${args.length ? ` ${args.join(" ")}` : ""})`;
  }
  if (info.kind === "event") {
    return `(gr-emit ${JSON.stringify(info.name)}${args.length ? ` ${args.join(" ")}` : ""})`;
  }
  if (info.kind === "special-gmode") {
    return `(gr-emit "gui-set-alpha" ${info.alpha(args)})`;
  }
  if (info.kind === "special-pos") {
    return `(progn (gr-set "__pos_x" ${args[0] || "0"}) (gr-set "__pos_y" ${args[1] || "0"}))`;
  }
  if (info.kind === "special-gcopy") {
    return `(gr-emit "gui-draw-image-scaled" ${info.render(args)})`;
  }
  if (info.kind === "noop") {
    return "(progn nil)";
  }
  throw unsupported(expr, ctx, "unsupported call target");
}

function isAwaitNoop(call) {
  return ts.isPropertyAccessExpression(call.expression)
    && ts.isIdentifier(call.expression.expression)
    && call.expression.expression.text === "Adap"
    && call.expression.name.text === "await_";
}

function classifyCall(call, ctx) {
  if (ts.isIdentifier(call.expression) && call.expression.text === "cursorBeep") {
    return { kind: "noop" };
  }
  if (!ts.isPropertyAccessExpression(call.expression)) throw unsupported(call, ctx, "call target");
  const root = call.expression.expression;
  const method = call.expression.name.text;
  if (ts.isIdentifier(root) && (root.text === "Func" || root.text === "Stand" || root.text === "Enemy")) {
    if (/^func[\dA-Za-z]+$/i.test(method) || /^setMessage$/.test(method) || /^AutoDraw$/.test(method) || /^funcLangDisplay$/.test(method)) {
      if (method === "AutoDraw") return { kind: "event", name: "game-auto-draw" };
      if (method === "setMessage") return { kind: "event", name: "game-set-message" };
      return { kind: "core-call", name: method };
    }
    throw unsupported(call, ctx, `${root.text}.${method}`);
  }
  if (ts.isIdentifier(root) && root.text === "Music") {
    return { kind: "event", name: `music-${method}` };
  }
  if (ts.isIdentifier(root) && root.text === "Adap") {
    const eventMap = {
      DSPLAY: "dtw-play-sound",
      gsel: "gui-select-buffer",
      redraw: "gui-present",
      color: "gui-set-color",
      boxf: "gui-fill-rect",
      line: "gui-draw-line",
      pset: "gui-draw-point",
      objsel: "dtw-object-select",
      dialog: "dtw-dialog",
    };
    if (eventMap[method]) return { kind: "event", name: eventMap[method] };
    if (method === "wait" || method === "await_") return { kind: "noop" };
    if (method === "gmode") {
      return {
        kind: "special-gmode",
        alpha(args) {
          if (args.length >= 4) return `(if (or (equal ${args[0]} 3) (equal ${args[0]} 4)) (gr-num ${args[3]}) 255)`;
          return "255";
        },
      };
    }
    if (method === "pos") return { kind: "special-pos" };
    if (method === "gcopy") {
      return {
        kind: "special-gcopy",
        render(args) {
          const destX = '(or (gr-get "__pos_x") 0)';
          const destY = '(or (gr-get "__pos_y") 0)';
          const destW = args[5] || args[3] || "0";
          const destH = args[6] || args[4] || "0";
          return `${args[0] || "0"} ${args[1] || "0"} ${args[2] || "0"} ${args[3] || "0"} ${args[4] || "0"} ${destX} ${destY} ${destW} ${destH}`;
        },
      };
    }
    throw unsupported(call, ctx, `Adap.${method}`);
  }
  if (ts.isIdentifier(root) && root.text === "console") {
    return { kind: "noop" };
  }
  throw unsupported(call, ctx, "call root");
}

function emitTarget(node, ctx) {
  if (ts.isIdentifier(node) && ctx.locals.includes(node.text)) {
    return {
      read: node.text,
      write(value) { return `(setq ${node.text} ${value})`; },
    };
  }
  if (ts.isPropertyAccessExpression(node)) {
    if (isGvarPropertyAccess(node)) {
      const slot = extractGvarSlot(node, ctx);
      return {
        read: `(gr-get ${emitSlotKey(slot)})`,
        write(value) { return `(gr-set ${emitSlotKey(slot)} ${value})`; },
      };
    }
    const base = emitValue(node.expression, ctx);
    const prop = JSON.stringify(node.name.text);
    return {
      read: `(gr-prop-ref ${base} ${prop})`,
      write(value) { return `(gr-prop-set ${base} ${prop} ${value})`; },
    };
  }
  if (ts.isElementAccessExpression(node)) {
    const arr = emitValue(node.expression, ctx);
    const index = emitValue(node.argumentExpression, ctx);
    return {
      read: `(gr-index-ref ${arr} ${index})`,
      write(value) {
        return `(let ((arr ${arr}) (idx ${index}) (val ${value})) (when (and (arrayp arr) (integerp idx) (>= idx 0) (< idx (length arr))) (aset arr idx val)))`;
      },
    };
  }
  throw unsupported(node, ctx, "target");
}

function emitCondition(node, ctx) {
  if (ts.isParenthesizedExpression(node)) return emitCondition(node.expression, ctx);
  if (ts.isPrefixUnaryExpression(node) && node.operator === ts.SyntaxKind.ExclamationToken) {
    return `(not ${emitCondition(node.operand, ctx)})`;
  }
  if (ts.isCallExpression(node) && ts.isIdentifier(node.expression) && node.expression.text === "noAbilityActive") {
    return "(and (equal (gr-get 1240) 0) (equal (gr-get 1999) 0) (equal (gr-get 2000) 0) (equal (gr-get 2001) 0) (equal (gr-get 1950) 0) (equal (gr-get 2002) 0) (equal (gr-get 2003) 0) (equal (gr-get 2004) 0) (equal (gr-get 2005) 0) (equal (gr-get 2006) 0) (equal (gr-get 2007) 0))";
  }
  if (ts.isBinaryExpression(node)) {
    const op = node.operatorToken.kind;
    if (op === ts.SyntaxKind.AmpersandAmpersandToken) {
      return `(and ${emitCondition(node.left, ctx)} ${emitCondition(node.right, ctx)})`;
    }
    if (op === ts.SyntaxKind.BarBarToken) {
      return `(or ${emitCondition(node.left, ctx)} ${emitCondition(node.right, ctx)})`;
    }
    const lhs = emitValue(node.left, ctx);
    const rhs = emitValue(node.right, ctx);
    switch (op) {
      case ts.SyntaxKind.EqualsEqualsToken:
      case ts.SyntaxKind.EqualsEqualsEqualsToken:
        return `(equal ${lhs} ${rhs})`;
      case ts.SyntaxKind.ExclamationEqualsToken:
      case ts.SyntaxKind.ExclamationEqualsEqualsToken:
        return `(not (equal ${lhs} ${rhs}))`;
      case ts.SyntaxKind.GreaterThanToken:
        return `(> ${emitNumericValue(node.left, ctx)} ${emitNumericValue(node.right, ctx)})`;
      case ts.SyntaxKind.GreaterThanEqualsToken:
        return `(>= ${emitNumericValue(node.left, ctx)} ${emitNumericValue(node.right, ctx)})`;
      case ts.SyntaxKind.LessThanToken:
        return `(< ${emitNumericValue(node.left, ctx)} ${emitNumericValue(node.right, ctx)})`;
      case ts.SyntaxKind.LessThanEqualsToken:
        return `(<= ${emitNumericValue(node.left, ctx)} ${emitNumericValue(node.right, ctx)})`;
      default:
        throw unsupported(node, ctx, "if condition");
    }
  }
  return emitTruth(node, ctx);
}

function emitLoopCondition(node, ctx) {
  if (node.kind === ts.SyntaxKind.TrueKeyword) return "t";
  return emitCondition(node, ctx);
}

function emitNumericValue(node, ctx) {
  return `(gr-num ${emitValue(node, ctx)})`;
}

function emitTruth(node, ctx) {
  const value = emitValue(node, ctx);
  return `(not (or (equal ${value} nil) (equal ${value} 0)))`;
}

function emitValue(node, ctx) {
  if (!node) return "nil";
  if (ts.isParenthesizedExpression(node)) return emitValue(node.expression, ctx);
  if (ts.isNumericLiteral(node)) return String(Number(node.text));
  if (ts.isStringLiteral(node)) return JSON.stringify(node.text);
  if (node.kind === ts.SyntaxKind.TrueKeyword) return "t";
  if (node.kind === ts.SyntaxKind.FalseKeyword) return "nil";
  if (node.kind === ts.SyntaxKind.NullKeyword) return "nil";
  if (ts.isIdentifier(node)) {
    if (ctx.locals.includes(node.text)) return node.text;
    throw unsupported(node, ctx, `identifier ${node.text}`);
  }
  if (ts.isPropertyAccessExpression(node)) {
    if (isGvarPropertyAccess(node)) {
      return `(gr-get ${emitSlotKey(extractGvarSlot(node, ctx))})`;
    }
    return `(gr-prop-ref ${emitValue(node.expression, ctx)} ${JSON.stringify(node.name.text)})`;
  }
  if (ts.isElementAccessExpression(node)) {
    return `(gr-index-ref ${emitValue(node.expression, ctx)} ${emitValue(node.argumentExpression, ctx)})`;
  }
  if (ts.isPrefixUnaryExpression(node) && node.operator === ts.SyntaxKind.MinusToken) {
    return `(- ${emitNumericValue(node.operand, ctx)})`;
  }
  if (ts.isBinaryExpression(node)) {
    if (node.operatorToken.kind === ts.SyntaxKind.PlusToken && isStringConcatExpression(node)) {
      return `(concat (format "%s" ${emitValue(node.left, ctx)}) (format "%s" ${emitValue(node.right, ctx)}))`;
    }
    const lhs = emitNumericValue(node.left, ctx);
    const rhs = emitNumericValue(node.right, ctx);
    switch (node.operatorToken.kind) {
      case ts.SyntaxKind.PlusToken:
        return `(+ ${lhs} ${rhs})`;
      case ts.SyntaxKind.MinusToken:
        return `(- ${lhs} ${rhs})`;
      case ts.SyntaxKind.AsteriskToken:
        return `(* ${lhs} ${rhs})`;
      case ts.SyntaxKind.SlashToken:
        return `(/ ${lhs} ${rhs})`;
      default:
        throw unsupported(node, ctx, "value binary expression");
    }
  }
  if (ts.isAwaitExpression(node)) {
    if (ts.isCallExpression(node.expression) && isAwaitNoop(node.expression)) return "nil";
    return emitValue(node.expression, ctx);
  }
  if (ts.isCallExpression(node)) {
    if (!ts.isPropertyAccessExpression(node.expression)) throw unsupported(node, ctx, "value call");
    const root = node.expression.expression;
    const method = node.expression.name.text;
    if (ts.isIdentifier(root) && root.text === "Math") {
      if (method === "floor") return `(floor ${emitNumericValue(node.arguments[0], ctx)})`;
      throw unsupported(node, ctx, `Math.${method}`);
    }
    if (ts.isIdentifier(root) && root.text === "Adap") {
      if (method === "rnd") return `(gr-random ${emitNumericValue(node.arguments[0], ctx)})`;
      if (method === "int") return `(truncate (gr-num ${emitValue(node.arguments[0], ctx)}))`;
      if (method === "getkey") return `(gr-index-ref (gr-get "pushing_key_list") ${emitValue(node.arguments[0], ctx)})`;
      if (method === "stick" || method === "ginfo" || method === "ck_joystick") return "0";
      if (method === "dim") return `(make-vector (gr-num ${emitValue(node.arguments[0], ctx)}) 0)`;
    }
    if (ts.isIdentifier(root) && root.text === "Func" && method === "func080") return "nil";
    throw unsupported(node, ctx, `value call ${method}`);
  }
  throw unsupported(node, ctx, "value");
}

function isStringConcatExpression(node) {
  if (ts.isStringLiteral(node)) return true;
  if (ts.isBinaryExpression(node) && node.operatorToken.kind === ts.SyntaxKind.PlusToken) {
    return isStringConcatExpression(node.left) || isStringConcatExpression(node.right);
  }
  return false;
}

function isGvarPropertyAccess(node) {
  return ts.isIdentifier(node.expression) && node.expression.text === "Gvar";
}

function extractGvarSlot(node, ctx) {
  if (!ts.isPropertyAccessExpression(node)) throw unsupported(node, ctx, "non-Gvar slot");
  if (!isGvarPropertyAccess(node)) throw unsupported(node, ctx, "non-Gvar access");
  const match = /^var_(\d+)$/.exec(node.name.text);
  if (match) return Number(match[1]);
  return node.name.text;
}

function emitSlotKey(slot) {
  return typeof slot === "number" ? String(slot) : JSON.stringify(slot);
}

function emitAdd(leftValue, rightValue, rightNode, ctx) {
  return isStringConcatExpression(rightNode)
    ? `(concat (format "%s" ${leftValue}) (format "%s" ${rightValue}))`
    : `(+ (gr-num ${leftValue}) (gr-num ${rightValue}))`;
}

function extractNumericLiteral(node, ctx) {
  if (!ts.isNumericLiteral(node)) throw unsupported(node, ctx, "non-numeric literal");
  return Number(node.text);
}

function isDebugPrint(expr) {
  return ts.isCallExpression(expr)
    && ts.isPropertyAccessExpression(expr.expression)
    && ts.isIdentifier(expr.expression.expression)
    && expr.expression.expression.text === "Adap"
    && expr.expression.name.text === "dbgprt"
    && expr.arguments.length === 1;
}

function indent(level) {
  return "  ".repeat(level);
}

function unsupported(node, ctx, detail) {
  const snippet = node.getText(ctx.sf).replace(/\s+/g, " ").trim();
  return new Error(`${ctx.name}: unsupported ${detail}: ${snippet}`);
}

module.exports = {
  transpileFunc,
};
