#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const ts = require("typescript");

const repoRoot = path.resolve(__dirname, "..");

if (require.main === module) {
  main();
}

function main() {
  const args = process.argv.slice(2);
  const srcRoot = path.resolve(
    valueAfter(args, "--src-root") || path.join(repoRoot, "src", "renderer", "func")
  );
  const outPath = path.resolve(
    valueAfter(args, "--out") || path.join(repoRoot, "nelisp_runtime", "gamedata-conditional.el")
  );
  let names = valuesAfter(args, "--name");
  const namesFile = valueAfter(args, "--names-file");
  if (namesFile) {
    names = names.concat(
      fs.readFileSync(path.resolve(namesFile), "utf8").split(/\s+/).filter(Boolean)
    );
  }
  if (!fs.existsSync(srcRoot)) throw new Error(`--src-root missing or not found: ${srcRoot}`);
  if (names.length === 0) throw new Error("pass at least one --name funcNNN or --names-file");

  const translated = [];
  const failed = [];
  for (const name of dedupe(names).sort(byFuncNumber)) {
    const file = path.join(srcRoot, `${name}.ts`);
    if (!fs.existsSync(file)) {
      failed.push([name, "missing .ts"]);
      continue;
    }
    try {
      translated.push({
        name,
        body: transpileFunc(name, file),
      });
    } catch (error) {
      failed.push([name, error.message]);
    }
  }

  const output = [
    ";;; gamedata-conditional.el --- generated native conditional funcs for NeLisp -*- coding: utf-8; -*-",
    ";; Generated by tools/generate_nelisp_conditional_runtime.js from src/renderer/func/*.ts.",
    ";; Do not edit by hand.",
    "",
    ...translated.flatMap(({ name, body }) => [
      `(defun gr-native-${name} (&rest _args)`,
      body.map((line) => `  ${line}`).join("\n"),
      ")",
      "",
      `(gr-defnative "${name}" #'gr-native-${name})`,
      "",
    ]),
    "(provide 'gamedata-conditional)",
    "",
  ].join("\n");

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, output, "utf8");
  console.log(JSON.stringify({
    out: path.relative(repoRoot, outPath),
    translated: translated.map((entry) => entry.name),
    failed,
  }, null, 2));
}

function valueAfter(args, flag) {
  const index = args.indexOf(flag);
  return index >= 0 ? args[index + 1] : null;
}

function valuesAfter(args, flag) {
  const out = [];
  for (let i = 0; i < args.length; i++) {
    if (args[i] === flag) out.push(args[i + 1]);
  }
  return out;
}

function dedupe(values) {
  return [...new Set(values)];
}

function byFuncNumber(a, b) {
  const na = Number(a.replace(/\D/g, ""));
  const nb = Number(b.replace(/\D/g, ""));
  return na - nb || a.localeCompare(b);
}

function transpileFunc(name, file) {
  const source = fs.readFileSync(file, "utf8");
  const sf = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const func = sf.statements.find((stmt) => ts.isFunctionDeclaration(stmt) && stmt.name && stmt.name.text === name);
  if (!func || !func.body) throw new Error(`function ${name} not found`);

  const lines = [];
  const ctx = { name, sf };
  const bodyStatements = func.body.statements.filter((stmt) => !isGeneratedGuard(stmt));
  if (bodyStatements.length === 0) throw new Error(`${name}: empty function body`);
  lines.push(`"${name}: transpiled from TypeScript conditional fallback."`);
  lines.push("(catch 'gr-return");
  for (const stmt of bodyStatements) {
    emitStatement(stmt, lines, 1, ctx);
  }
  lines.push(")");
  return lines;
}

function isGeneratedGuard(stmt) {
  if (!ts.isIfStatement(stmt)) return false;
  const cond = stmt.expression;
  if (!ts.isCallExpression(cond)) return false;
  if (!ts.isIdentifier(cond.expression) || cond.expression.text !== "shouldUseGeneratedGameFunction") return false;
  if (cond.arguments.length !== 1 || !ts.isStringLiteral(cond.arguments[0])) return false;
  if (!stmt.thenStatement || !ts.isBlock(stmt.thenStatement)) return false;
  const inner = stmt.thenStatement.statements;
  if (inner.length !== 2) return false;
  return ts.isExpressionStatement(inner[0]) && ts.isReturnStatement(inner[1]);
}

function emitStatement(stmt, lines, level, ctx) {
  if (ts.isExpressionStatement(stmt)) {
    emitExpressionStatement(stmt.expression, lines, level, ctx);
    return;
  }
  if (ts.isIfStatement(stmt)) {
    emitIf(stmt, lines, level, ctx);
    return;
  }
  if (ts.isReturnStatement(stmt)) {
    if (stmt.expression) throw unsupported(stmt, ctx, "return with value");
    lines.push(`${indent(level)}(throw 'gr-return nil)`);
    return;
  }
  throw unsupported(stmt, ctx, ts.SyntaxKind[stmt.kind]);
}

function emitExpressionStatement(expr, lines, level, ctx) {
  if (isDebugPrint(expr)) {
    lines.push(`${indent(level)}(push ${extractNumericLiteral(expr.arguments[0], ctx)} gr-trace)`);
    return;
  }

  if (ts.isBinaryExpression(expr) && expr.operatorToken.kind === ts.SyntaxKind.FirstAssignment) {
    emitAssignment(expr.left, expr.right, lines, level, ctx);
    return;
  }

  if (ts.isCallExpression(expr) || (ts.isAwaitExpression(expr) && ts.isCallExpression(expr.expression))) {
    lines.push(`${indent(level)}${emitCall(expr, ctx)}`);
    return;
  }

  throw unsupported(expr, ctx, "expression statement");
}

function emitAssignment(left, right, lines, level, ctx) {
  const target = emitTarget(left, ctx);
  if (target.kind === "slot") {
    lines.push(`${indent(level)}(gr-set ${emitSlotKey(target.slot)} ${emitValue(right, ctx)})`);
    return;
  }
  if (target.kind === "index") {
    lines.push(`${indent(level)}(let ((arr ${target.arr}) (idx ${target.index}) (val ${emitValue(right, ctx)}))`);
    lines.push(`${indent(level + 1)}(when (and (arrayp arr) (integerp idx) (>= idx 0) (< idx (length arr)))`);
    lines.push(`${indent(level + 2)}(aset arr idx val)))`);
    return;
  }
  throw unsupported(left, ctx, "assignment target");
}

function emitIf(stmt, lines, level, ctx) {
  const cond = emitCondition(stmt.expression, ctx);
  const thenLines = emitBranch(stmt.thenStatement, level + 1, ctx);
  const elseLines = stmt.elseStatement ? emitBranch(stmt.elseStatement, level + 1, ctx) : [];
  lines.push(`${indent(level)}(if ${cond}`);
  lines.push(...wrapBranch(thenLines, level + 1));
  if (stmt.elseStatement) {
    lines.push(...wrapBranch(elseLines, level + 1));
  }
  lines.push(`${indent(level)})`);
}

function emitBranch(node, level, ctx) {
  const branchLines = [];
  if (ts.isBlock(node)) {
    for (const stmt of node.statements) emitStatement(stmt, branchLines, level, ctx);
    return branchLines;
  }
  emitStatement(node, branchLines, level, ctx);
  return branchLines;
}

function wrapBranch(lines, level) {
  if (lines.length === 0) return [`${indent(level)}nil`];
  if (lines.length === 1) return [lines[0]];
  return [
    `${indent(level)}(progn`,
    ...lines.map((line) => `${indent(1)}${line}`),
    `${indent(level)})`,
  ];
}

function emitCall(expr, ctx) {
  const call = ts.isAwaitExpression(expr) ? expr.expression : expr;
  if (!ts.isCallExpression(call)) throw unsupported(expr, ctx, "non-call");
  const info = classifyCall(call, ctx);
  const args = call.arguments.map((arg) => emitValue(arg, ctx));

  if (info.kind === "core-call") {
    return `(gr-run-func ${JSON.stringify(info.name)}${args.length ? ` ${args.join(" ")}` : ""})`;
  }
  if (info.kind === "event") {
    return `(gr-emit ${JSON.stringify(info.name)}${args.length ? ` ${args.join(" ")}` : ""})`;
  }
  throw unsupported(expr, ctx, "unsupported call target");
}

function classifyCall(call, ctx) {
  if (!ts.isPropertyAccessExpression(call.expression)) throw unsupported(call, ctx, "call target");
  const root = call.expression.expression;
  const method = call.expression.name.text;
  if (ts.isIdentifier(root) && root.text === "Func") {
    if (/^func\d+[a-z]*$/i.test(method)) {
      return { kind: "core-call", name: method };
    }
    if (method === "AutoDraw") return { kind: "event", name: "game-auto-draw" };
    if (method === "setMessage") return { kind: "event", name: "game-set-message" };
    throw unsupported(call, ctx, `Func.${method}`);
  }
  if (ts.isIdentifier(root) && root.text === "Adap") {
    if (method === "DSPLAY") return { kind: "event", name: "dtw-play-sound" };
    throw unsupported(call, ctx, `Adap.${method}`);
  }
  throw unsupported(call, ctx, "call root");
}

function emitTarget(node, ctx) {
  if (ts.isPropertyAccessExpression(node)) {
    return { kind: "slot", slot: extractGvarSlot(node, ctx) };
  }
  if (ts.isElementAccessExpression(node)) {
    return {
      kind: "index",
      arr: emitValue(node.expression, ctx),
      index: emitValue(node.argumentExpression, ctx),
    };
  }
  throw unsupported(node, ctx, "target");
}

function emitCondition(node, ctx) {
  if (ts.isParenthesizedExpression(node)) return emitCondition(node.expression, ctx);
  if (ts.isPrefixUnaryExpression(node) && node.operator === ts.SyntaxKind.ExclamationToken) {
    return `(not ${emitCondition(node.operand, ctx)})`;
  }
  if (ts.isBinaryExpression(node)) {
    const op = node.operatorToken.kind;
    if (op === ts.SyntaxKind.AmpersandAmpersandToken) {
      return `(and ${emitCondition(node.left, ctx)} ${emitCondition(node.right, ctx)})`;
    }
    if (op === ts.SyntaxKind.BarBarToken) {
      return `(or ${emitCondition(node.left, ctx)} ${emitCondition(node.right, ctx)})`;
    }
    const lhs = emitValue(node.left, ctx);
    const rhs = emitValue(node.right, ctx);
    switch (op) {
      case ts.SyntaxKind.EqualsEqualsToken:
      case ts.SyntaxKind.EqualsEqualsEqualsToken:
        return `(equal ${lhs} ${rhs})`;
      case ts.SyntaxKind.ExclamationEqualsToken:
      case ts.SyntaxKind.ExclamationEqualsEqualsToken:
        return `(not (equal ${lhs} ${rhs}))`;
      case ts.SyntaxKind.GreaterThanToken:
        return `(> ${lhs} ${rhs})`;
      case ts.SyntaxKind.GreaterThanEqualsToken:
        return `(>= ${lhs} ${rhs})`;
      case ts.SyntaxKind.LessThanToken:
        return `(< ${lhs} ${rhs})`;
      case ts.SyntaxKind.LessThanEqualsToken:
        return `(<= ${lhs} ${rhs})`;
      default:
        throw unsupported(node, ctx, "if condition");
    }
  }
  return emitTruth(node, ctx);
}

function emitTruth(node, ctx) {
  const value = emitValue(node, ctx);
  return `(not (equal ${value} 0))`;
}

function emitValue(node, ctx) {
  if (ts.isParenthesizedExpression(node)) return emitValue(node.expression, ctx);
  if (ts.isNumericLiteral(node)) return String(Number(node.text));
  if (ts.isStringLiteral(node)) return JSON.stringify(node.text);
  if (node.kind === ts.SyntaxKind.TrueKeyword) return "t";
  if (node.kind === ts.SyntaxKind.FalseKeyword) return "nil";
  if (ts.isPropertyAccessExpression(node)) {
    return `(gr-get ${emitSlotKey(extractGvarSlot(node, ctx))})`;
  }
  if (ts.isElementAccessExpression(node)) {
    return `(gr-index-ref ${emitValue(node.expression, ctx)} ${emitValue(node.argumentExpression, ctx)})`;
  }
  if (ts.isPrefixUnaryExpression(node) && node.operator === ts.SyntaxKind.MinusToken) {
    return `(- ${emitValue(node.operand, ctx)})`;
  }
  if (ts.isBinaryExpression(node)) {
    const lhs = emitValue(node.left, ctx);
    const rhs = emitValue(node.right, ctx);
    switch (node.operatorToken.kind) {
      case ts.SyntaxKind.PlusToken:
        return `(+ ${lhs} ${rhs})`;
      case ts.SyntaxKind.MinusToken:
        return `(- ${lhs} ${rhs})`;
      case ts.SyntaxKind.AsteriskToken:
        return `(* ${lhs} ${rhs})`;
      case ts.SyntaxKind.SlashToken:
        return `(/ ${lhs} ${rhs})`;
      default:
        throw unsupported(node, ctx, "value binary expression");
    }
  }
  if (ts.isCallExpression(node)) {
    if (!ts.isPropertyAccessExpression(node.expression)) throw unsupported(node, ctx, "value call");
    const root = node.expression.expression;
    const method = node.expression.name.text;
    if (ts.isIdentifier(root) && root.text === "Adap" && method === "rnd") {
      if (node.arguments.length !== 1) throw unsupported(node, ctx, "Adap.rnd arity");
      return `(gr-random ${emitValue(node.arguments[0], ctx)})`;
    }
    throw unsupported(node, ctx, `value call ${method}`);
  }
  throw unsupported(node, ctx, "value");
}

function extractGvarSlot(node, ctx) {
  if (!ts.isPropertyAccessExpression(node)) throw unsupported(node, ctx, "non-Gvar slot");
  if (!ts.isIdentifier(node.expression) || node.expression.text !== "Gvar") {
    throw unsupported(node, ctx, "non-Gvar access");
  }
  const match = /^var_(\d+)$/.exec(node.name.text);
  if (match) return Number(match[1]);
  return node.name.text;
}

function emitSlotKey(slot) {
  return typeof slot === "number" ? String(slot) : JSON.stringify(slot);
}

function extractNumericLiteral(node, ctx) {
  if (!ts.isNumericLiteral(node)) throw unsupported(node, ctx, "non-numeric literal");
  return Number(node.text);
}

function isDebugPrint(expr) {
  return ts.isCallExpression(expr)
    && ts.isPropertyAccessExpression(expr.expression)
    && ts.isIdentifier(expr.expression.expression)
    && expr.expression.expression.text === "Adap"
    && expr.expression.name.text === "dbgprt"
    && expr.arguments.length === 1;
}

function indent(level) {
  return "  ".repeat(level);
}

function unsupported(node, ctx, detail) {
  const snippet = node.getText(ctx.sf).replace(/\s+/g, " ").trim();
  return new Error(`${ctx.name}: unsupported ${detail}: ${snippet}`);
}

module.exports = {
  transpileFunc,
};
