// statediff_to_elisp.mjs — export the migrated state-diff IR to an elisp data
// file the NeLisp game-runner interprets.  The IR is pure JSON-like data, so we
// read the generated .ts source, slice out the object literal (keys are quoted,
// values are JSON arrays => valid JSON) and re-emit it as s-expressions:
// array -> (...), string -> "...", number -> number, null -> nil.
//
//   node tools/statediff_to_elisp.mjs [out.el]
import { writeFileSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const out = process.argv[2] || 'nelisp_runtime/gamedata-simple.el';

const ENTRY_OPS = new Set([
  'core-call',
  'dtw-debug-print',
  'index-set',
]);

const EXPR_OPS = new Set([
  'state-slot-ref',
  'math-add',
  'math-sub',
  'math-mul',
  'math-div',
  'math-floor',
  'math-trunc',
  'math-abs',
  'math-mod',
  'bitwise-and',
  'bitwise-or',
  'bitwise-xor',
  'dtw-random',
  'dtw-read-key-state',
  'index-ref',
  'i18n-format',
]);

function esc(s) { return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"'); }
function isExprNode(v) {
  return Array.isArray(v)
    && v.length === 1
    && Array.isArray(v[0])
    && typeof v[0][0] === 'string'
    && EXPR_OPS.has(v[0][0]);
}

function isEntryNode(v) {
  return Array.isArray(v)
    && v.length > 0
    && typeof v[0] === 'string'
    && (ENTRY_OPS.has(v[0]) || v[0].startsWith('dtw-') || v[0].startsWith('game-'));
}

function toElisp(v, mode = 'value') {
  if (Array.isArray(v)) {
    if (mode === 'entry' && typeof v[0] === 'string') {
      return '(' + [v[0], ...v.slice(1).map((item) => toElisp(item, 'value'))].join(' ') + ')';
    }
    if (mode === 'expr' && typeof v[0] === 'string') {
      return '(' + [v[0], ...v.slice(1).map((item) => toElisp(item, 'value'))].join(' ') + ')';
    }
    if (isExprNode(v)) return '(' + v.map((item) => toElisp(item, 'expr')).join(' ') + ')';
    if (isEntryNode(v)) return toElisp(v, 'entry');
    return '(' + v.map((item) => toElisp(item, 'value')).join(' ') + ')';
  }
  if (v === null || v === undefined) return 'nil';
  if (typeof v === 'string') return '"' + esc(v) + '"';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 't' : 'nil';
  return 'nil';
}

// Extract the first top-level `= { ... }` object literal from a generated .ts.
function loadTsObject(tsPath) {
  const txt = readFileSync(tsPath, 'utf8');
  const eq = txt.indexOf('= {');
  if (eq < 0) throw new Error(`no object literal in ${tsPath}`);
  const start = txt.indexOf('{', eq);
  const end = txt.lastIndexOf('}');
  const json = txt.slice(start, end + 1).replace(/,(\s*[}\]])/g, '$1'); // strip trailing commas
  return JSON.parse(json);
}

const sources = [
  'src/renderer/nelisp_bridge/generatedSimpleStateDiff.ts',
];

const lines = [
  ';;; gamedata-simple.el --- generated state-diff IR (do not edit) -*- coding: utf-8; lexical-binding: t; -*-',
  ';; Generated by tools/statediff_to_elisp.mjs from the migrated state-diff data.',
  '',
];
let count = 0;
for (const rel of sources) {
  const data = loadTsObject(resolve(process.cwd(), rel));
  for (const [name, ir] of Object.entries(data)) {
    lines.push(`(gr-defun ${JSON.stringify(name)} '${toElisp(ir)})`);
    count++;
  }
}
lines.push('');
lines.push("(provide 'gamedata-simple)");
lines.push('');
writeFileSync(out, lines.join('\n'), 'utf8');
console.error(`OK: ${count} functions -> ${out}`);
