// statediff_to_elisp.mjs — export the migrated state-diff IR to an elisp data
// file the NeLisp game-runner interprets.  The IR is pure JSON-like data, so we
// read the generated .ts source, slice out the object literal (keys are quoted,
// values are JSON arrays => valid JSON) and re-emit it as s-expressions:
// array -> (...), string -> "...", number -> number, null -> nil.
//
//   node tools/statediff_to_elisp.mjs [out.el]
import { writeFileSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const out = process.argv[2] || 'nelisp_runtime/gamedata-simple.el';

function esc(s) { return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"'); }
function toElisp(v) {
  if (Array.isArray(v)) return '(' + v.map(toElisp).join(' ') + ')';
  if (v === null || v === undefined) return 'nil';
  if (typeof v === 'string') return '"' + esc(v) + '"';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 't' : 'nil';
  return 'nil';
}

// Extract the first top-level `= { ... }` object literal from a generated .ts.
function loadTsObject(tsPath) {
  const txt = readFileSync(tsPath, 'utf8');
  const eq = txt.indexOf('= {');
  if (eq < 0) throw new Error(`no object literal in ${tsPath}`);
  const start = txt.indexOf('{', eq);
  const end = txt.lastIndexOf('}');
  const json = txt.slice(start, end + 1).replace(/,(\s*[}\]])/g, '$1'); // strip trailing commas
  return JSON.parse(json);
}

const sources = [
  'src/renderer/nelisp_bridge/generatedSimpleStateDiff.ts',
];

const lines = [
  ';;; gamedata-simple.el --- generated state-diff IR (do not edit) -*- coding: utf-8; -*-',
  ';; Generated by tools/statediff_to_elisp.mjs from the migrated state-diff data.',
  '',
];
let count = 0;
for (const rel of sources) {
  const data = loadTsObject(resolve(process.cwd(), rel));
  for (const [name, ir] of Object.entries(data)) {
    lines.push(`(gr-defun ${JSON.stringify(name)} '${toElisp(ir)})`);
    count++;
  }
}
lines.push('');
lines.push("(provide 'gamedata-simple)");
lines.push('');
writeFileSync(out, lines.join('\n'), 'utf8');
console.error(`OK: ${count} functions -> ${out}`);
